import { useEffect, useRef, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useOperations, type ArenaProject, type InventoryItem, type Student, type TeamMember } from '../features/operations/DemoDataProvider'
import { Breadcrumb, DetailList, Empty, Feedback, Field, Group, Heading, ListSummary, NoAccess, Notes, Pagination, SaveRow, Search, Status, currency, displayDate, quantity, today, useFilters, useSave } from './arenaUi'

const blankStudent = (): Omit<Student, 'id'> => ({ name: '', phone: '', birthDate: '', address: '', shirtSize: '', shortsSize: '', weeklyClasses: '1', days: '', class1: '', class2: '', monthlyAmount: 0, paymentStatus: 'A confirmar', paymentDate: '', statementName: '', status: 'A confirmar', notes: '' })
export function StudentsPage() {
  const data = useOperations(); const filters = useFilters()
  if (!data.canRead('students')) return <NoAccess />
  const filtered = data.students.filter(student => `${student.name} ${student.phone}`.toLocaleLowerCase('pt-BR').includes(filters.query.toLocaleLowerCase('pt-BR')) && (!filters.status || student.status === filters.status))
  return <main className="operation-page arena-page"><Heading title="Alunos" description="Encontre um aluno e abra sua ficha. Matrículas, presença e cobranças têm registros próprios na Escola." action={data.canWrite('students') && <Link className="primary-link" to={filters.href('/alunos/novo')}>+ Adicionar aluno</Link>} /><Feedback />
    <div className="arena-actions"><Link className="secondary-link" to="/escola">Turmas e matrículas →</Link></div>
    <div className="arena-toolbar"><Search filters={filters} /><Field label="Situação" value={filters.status} onChange={value => filters.set('status', value)} options={[{ value: '', label: 'Todas' }, 'Ativo', 'A confirmar', 'Pausado', 'Inativo']} /></div><ListSummary count={filtered.length} label="alunos" />
    {filtered.length ? <Pagination total={filtered.length}>{(start,end) => <div className="record-list">{filtered.slice(start,end).map(student => <Link className="record-row" to={filters.href(`/alunos/${student.id}`)} key={student.id}><span className="record-avatar">{student.name.slice(0,1).toUpperCase()}</span><span className="record-main"><strong>{student.name}</strong><small>{student.weeklyClasses}x por semana · {student.days || 'Horário a definir'}</small></span><Status>{student.status}</Status><span className="row-arrow" aria-hidden="true">›</span></Link>)}</div>}</Pagination> : <Empty>{filters.query || filters.status ? 'Nenhum aluno corresponde aos filtros.' : 'Adicione o primeiro aluno para começar.'}</Empty>}
  </main>
}
export function StudentDetailsPage() {
  const { studentId } = useParams(); const navigate = useNavigate(); const data = useOperations(); const filters = useFilters(); const save = useSave(); const draftId = useRef(crypto.randomUUID())
  const existing = data.students.find(student => student.id === studentId); const isNew = studentId === 'novo'
  const [editing,setEditing] = useState(isNew); const [form,setForm] = useState<Omit<Student,'id'>>(() => existing ? {...existing} : blankStudent())
  useEffect(() => { if (existing && !editing) setForm({...existing}) },[existing,editing])
  const update = (key: keyof Omit<Student,'id'>,value: string) => setForm(current => ({...current,[key]:key === 'monthlyAmount' ? Number(value) : value}))
  async function submit(event:FormEvent) { event.preventDefault(); const id = await save.run(() => data.saveStudent(form,isNew ? draftId.current : studentId)); if(id) { setEditing(false); navigate(filters.href(`/alunos/${id}`)) } }
  if (!data.canRead('students') || isNew && !data.canWrite('students')) return <NoAccess />
  if (!isNew && !existing) return <main className="operation-page arena-page"><Feedback /><Empty>{data.persistenceStatus === 'connecting' ? 'Carregando a ficha…' : 'Não encontramos esse cadastro.'}</Empty><Link className="secondary-link" to={filters.href('/alunos')}>Voltar aos alunos</Link></main>
  return <main className="operation-page arena-page"><Breadcrumb to={filters.href('/alunos')} label="Alunos" /><Heading eyebrow={isNew ? 'Novo cadastro' : 'Ficha do aluno'} title={isNew ? 'Adicionar aluno' : existing!.name} description="Identificação, aulas e contatos. Os campos complementares podem ser preenchidos depois." action={!editing && data.canWrite('students') && <button className="secondary-link" onClick={() => setEditing(true)}>Editar dados</button>} /><Feedback action={save} />
    {(isNew || editing) && data.canWrite('students') ? <form className="operation-card operation-form" onSubmit={submit}><Group title="1. Identificação"><Field label="Nome" required value={form.name} onChange={v => update('name',v)} /><Field label="Telefone" type="tel" value={form.phone} onChange={v => update('phone',v)} /><Field label="Situação" value={form.status} onChange={v => update('status',v)} options={['A confirmar','Ativo','Pausado','Inativo']} /></Group>
      <Group title="2. Referência de aulas"><Field label="Aulas por semana" type="number" min={0} step="1" value={form.weeklyClasses} onChange={v => update('weeklyClasses',v)} /><Field label="Dias da semana" value={form.days} onChange={v => update('days',v)} placeholder="Ex.: Segunda-feira / Sábado" /><Field label="Turma ou horário 1" value={form.class1} onChange={v => update('class1',v)} placeholder="Ex.: 19:00 até 20:00" /><Field label="Turma ou horário 2" value={form.class2} onChange={v => update('class2',v)} placeholder="Opcional" /></Group>
      {data.canWrite('financeEntries')&&<Group title="3. Anotações de mensalidade"><Field label="Valor mensal (R$)" type="number" min={0} value={form.monthlyAmount} onChange={v => update('monthlyAmount',v)} /><Field label="Status do pagamento" value={form.paymentStatus} onChange={v => update('paymentStatus',v)} options={['A confirmar','Pago','Pendente','Isento','Desistiu']} /><Field label="Data do pagamento" type="date" value={form.paymentDate} onChange={v => update('paymentDate',v)} /><Field label="Nome no extrato" value={form.statementName} onChange={v => update('statementName',v)} /></Group>}<p className="arena-hint">Estas anotações históricas não geram recebimentos ou mensalidades. Registre a matrícula na Escola e a cobrança no Financeiro.</p>
      <Group title="4. Dados complementares"><Field label="Data de nascimento" type="date" value={form.birthDate} onChange={v => update('birthDate',v)} /><Field label="Endereço" value={form.address} onChange={v => update('address',v)} /><Field label="Tamanho de camiseta" value={form.shirtSize} onChange={v => update('shirtSize',v)} /><Field label="Tamanho de bermuda" value={form.shortsSize} onChange={v => update('shortsSize',v)} /><Notes value={form.notes} onChange={v => update('notes',v)} /></Group><SaveRow busy={save.busy} onCancel={() => isNew ? navigate(filters.href('/alunos')) : setEditing(false)} /></form> : <div className="detail-grid"><section className="operation-card"><h2>Aulas e referência de pagamentos</h2><DetailList items={[["Frequência",`${existing!.weeklyClasses}x por semana`],["Dias",existing!.days],["Turma 1",existing!.class1],["Turma 2",existing!.class2],...(data.canRead('financeEntries')?[["Mensalidade anotada",currency(existing!.monthlyAmount)],["Último status anotado",existing!.paymentStatus],["Data anotada",displayDate(existing!.paymentDate)],["Nome no extrato",existing!.statementName]] as [string,string][]:[["Informações financeiras","Acesso restrito"]] as [string,string][])]} /><p className="arena-hint">O status anotado não comprova recebimento financeiro.</p><Link className="secondary-link" to={`/escola/matriculas?student=${existing!.id}`}>Ver matrículas do aluno →</Link></section><section className="operation-card"><h2>Dados pessoais</h2><DetailList items={[["Telefone",existing!.phone],["Nascimento",displayDate(existing!.birthDate)],["Endereço",existing!.address],["Camiseta",existing!.shirtSize],["Bermuda",existing!.shortsSize],["Situação",existing!.status]]} />{existing!.notes && <p className="detail-notes">{existing!.notes}</p>}</section></div>}
  </main>
}

const blankTeam = (): Omit<TeamMember,'id'> => ({name:'',phone:'',role:'Professor de futevôlei',payAmount:0,payBasis:'Por hora',paymentFrequency:'Semanal',paymentDay:'',status:'Ativo',notes:''})
export function TeamPage() { return <TeamView /> }
export function TeamDetailsPage() { const {memberId} = useParams(); return <TeamView detailId={memberId} /> }
function TeamView({detailId}:{detailId?:string}) {
  const data=useOperations(); const filters=useFilters(); const save=useSave(); const draftId=useRef(crypto.randomUUID()); const existing=data.team.find(person=>person.id===detailId)
  const [form,setForm]=useState<Omit<TeamMember,'id'>|null>(null);const [editId,setEditId]=useState<string|undefined>()
  const open=(person?:TeamMember)=>{draftId.current=crypto.randomUUID();setEditId(person?.id);setForm(person?{...person}:blankTeam())}
  async function submit(event:FormEvent){event.preventDefault();if(!form)return;const id=await save.run(()=>data.saveTeamMember(form,editId??draftId.current));if(id){setForm(null);setEditId(undefined)}}
  if(!data.canRead('team'))return <NoAccess />
  const filtered=data.team.filter(person=>`${person.name} ${person.role}`.toLocaleLowerCase('pt-BR').includes(filters.query.toLocaleLowerCase('pt-BR'))&&(!filters.status||person.status===filters.status))
  return <main className="operation-page arena-page">{detailId&&<Breadcrumb to={filters.href('/equipe')} label="Equipe" />}<Heading title={detailId?existing?.name??'Ficha da equipe':'Equipe'} description="Pessoas, funções, contato e acordos de pagamento da arena." action={data.canWrite('team')&&<button className="primary-link" onClick={()=>open(existing)}>{detailId?'Editar dados':'+ Adicionar pessoa'}</button>} /><Feedback action={save} />
    {form&&<form className="operation-card operation-form" onSubmit={submit}><Group title="1. Pessoa e função"><Field label="Nome" required value={form.name} onChange={v=>setForm({...form,name:v})} /><Field label="Telefone" type="tel" value={form.phone} onChange={v=>setForm({...form,phone:v})} /><Field label="Função" value={form.role} onChange={v=>setForm({...form,role:v})} options={['Professor de futevôlei','Bar','Limpeza','Apoio operacional','Outra']} /><Field label="Situação" value={form.status} onChange={v=>setForm({...form,status:v})} options={['Ativo','A confirmar','Inativo']} /></Group>{data.canWrite('financeEntries')&&<Group title="2. Acordo de pagamento"><Field label="Valor combinado (R$)" type="number" min={0} value={form.payAmount} onChange={v=>setForm({...form,payAmount:Number(v)})} /><Field label="Base do valor" value={form.payBasis} onChange={v=>setForm({...form,payBasis:v})} options={['Por hora','Por dia','Por turno','Por aula','Valor mensal','Outro']} /><Field label="Frequência de pagamento" value={form.paymentFrequency} onChange={v=>setForm({...form,paymentFrequency:v})} options={['A combinar','Diário','Semanal','Quinzenal','Mensal']} /><Field label="Dia combinado para pagar" value={form.paymentDay} onChange={v=>setForm({...form,paymentDay:v})} placeholder="Ex.: toda sexta-feira" /><Notes label="Observações do acordo" value={form.notes} onChange={v=>setForm({...form,notes:v})} /></Group>}<p className="arena-hint">O acordo não gera uma despesa automaticamente. Registre o pagamento no Financeiro.</p><SaveRow busy={save.busy} onCancel={()=>setForm(null)} /></form>}
    {detailId?existing?<section className="operation-card"><h2>Ficha da pessoa</h2><DetailList items={[["Telefone",existing.phone],["Função",existing.role],["Situação",existing.status],...(data.canRead('financeEntries')?[["Valor combinado",currency(existing.payAmount)],["Base",existing.payBasis],["Frequência",existing.paymentFrequency],["Dia combinado",existing.paymentDay]] as [string,string][]:[["Acordo financeiro","Acesso restrito"]] as [string,string][])]} />{data.canRead('financeEntries')&&existing.notes&&<p className="detail-notes">{existing.notes}</p>}</section>:<Empty>{data.persistenceStatus==='connecting'?'Carregando a ficha…':'Pessoa não encontrada.'}</Empty>:<><div className="arena-toolbar"><Search filters={filters} /><Field label="Situação" value={filters.status} onChange={v=>filters.set('status',v)} options={[{value:'',label:'Todas'},'Ativo','A confirmar','Inativo']} /></div><ListSummary count={filtered.length} label="pessoas" />{filtered.length?<Pagination total={filtered.length}>{(start,end)=><div className="record-list">{filtered.slice(start,end).map(person=><article className="record-row" key={person.id}><span className="record-avatar gold-avatar">{person.name.slice(0,1).toUpperCase()}</span><span className="record-main"><strong>{person.name}</strong><small>{person.role}{data.canRead('financeEntries')&&<> · {person.payBasis} · pagamento {person.paymentFrequency.toLowerCase()}</>}</small></span><Status>{person.status}</Status>{data.canRead('financeEntries')&&<span className="pay-summary">{currency(person.payAmount)}</span>}<span className="arena-record-actions"><Link to={filters.href(`/equipe/${person.id}`)}>Ver ficha →</Link>{data.canWrite('team')&&<button className="text-button" onClick={()=>open(person)}>Editar</button>}</span></article>)}</div>}</Pagination>:<Empty>Cadastre professores, equipe do bar, limpeza e apoio operacional.</Empty>}</>}
  </main>
}

const blankInventory=():Omit<InventoryItem,'id'>=>({name:'',category:'Limpeza',unit:'unidade',quantity:0,minimum:0,unitCost:0,location:'',notes:'',paymentMethod:'A definir',movements:[]})
export function InventoryPage(){return <InventoryView />}
export function InventoryDetailsPage(){const{itemId}=useParams();return <InventoryView detailId={itemId} />}
function InventoryView({detailId}:{detailId?:string}){
  const data=useOperations();const filters=useFilters();const save=useSave();const draftId=useRef(crypto.randomUUID());const existing=data.inventory.find(item=>item.id===detailId)
  const[form,setForm]=useState<Omit<InventoryItem,'id'>|null>(null);const[editId,setEditId]=useState<string|undefined>()
  const open=(item?:InventoryItem)=>{draftId.current=crypto.randomUUID();setEditId(item?.id);setForm(item?{...item,movements:item.movements??[]}:blankInventory())}
  async function submit(event:FormEvent){event.preventDefault();if(!form)return;const id=await save.run(()=>data.saveInventoryItem(form,editId??draftId.current));if(id){setForm(null);setEditId(undefined)}}
  if(!data.canRead('inventory'))return <NoAccess />
  const filtered=data.inventory.filter(item=>`${item.name} ${item.category}`.toLocaleLowerCase('pt-BR').includes(filters.query.toLocaleLowerCase('pt-BR'))&&(filters.params.get('low')!=='1'||item.quantity<=item.minimum)&&(!filters.params.get('category')||item.category===filters.params.get('category')))
  const shown=detailId?existing?[existing]:[]:filtered
  return <main className="operation-page arena-page">{detailId&&<Breadcrumb to={filters.href('/estoque')} label="Materiais da arena" />}<Heading title={detailId?existing?.name??'Ficha do material':'Materiais da arena'} description="Bolas, limpeza, utensílios e equipamentos. Produtos para venda ficam no estoque do bar." action={data.canWrite('inventory')&&<button className="primary-link" onClick={()=>open(existing)}>{detailId?'Editar dados':'+ Adicionar item'}</button>} /><Feedback action={save} />
    {form&&<form className="operation-card operation-form" onSubmit={submit}><Group title="1. Identificação do material"><Field label="Material ou equipamento" required value={form.name} onChange={v=>setForm({...form,name:v})} /><Field label="Área" value={form.category} onChange={v=>setForm({...form,category:v})} options={['Limpeza','Bar','Material esportivo','Equipamento de ginástica','Administrativo','Outro']} /><Field label="Unidade" value={form.unit} onChange={v=>setForm({...form,unit:v})} options={['unidade','pacote','caixa','lata','garrafa','kg','litro','par']} /><Field label="Onde fica guardado" value={form.location} onChange={v=>setForm({...form,location:v})} /></Group><Group title="2. Quantidade e compra"><Field label="Quantidade atual" type="number" min={0} value={form.quantity} onChange={v=>setForm({...form,quantity:Number(v)})} /><Field label="Avisar quando chegar a" type="number" min={0} value={form.minimum} onChange={v=>setForm({...form,minimum:Number(v)})} />{data.canWrite('financeEntries')&&<Field label="Custo unitário estimado (R$)" type="number" min={0} value={form.unitCost} onChange={v=>setForm({...form,unitCost:Number(v)})} />}{data.canWrite('financeEntries')&&<Field label="Meio usual de compra" value={form.paymentMethod} onChange={v=>setForm({...form,paymentMethod:v})} options={['A definir','PagBank','Pix','Dinheiro','Cartão','Outro']} />}<Notes value={form.notes} onChange={v=>setForm({...form,notes:v})} /></Group><SaveRow busy={save.busy} onCancel={()=>setForm(null)} /></form>}
    {!detailId&&<div className="arena-toolbar"><Search filters={filters} /><Field label="Disponibilidade" value={filters.params.get('low')??''} onChange={v=>filters.set('low',v)} options={[{value:'',label:'Todos os materiais'},{value:'1',label:'No mínimo ou abaixo'}]} /></div>}{!detailId&&<ListSummary count={filtered.length} label="materiais" />}
    {shown.length?<div className="inventory-grid">{shown.map(item=><article className={`inventory-card ${item.quantity<=item.minimum?'is-low':''}`} key={item.id}><div className="inventory-title"><div><span className="eyebrow">{item.category}</span><h2>{item.name}</h2></div><span className="stock-number">{quantity(item.quantity)} <small>{item.unit}</small></span></div><p>{item.location||'Local não definido'}{item.quantity<=item.minimum&&<strong className="low-stock"> · Repor estoque</strong>}</p><div className="stock-controls">{data.canWrite('inventory')&&<><button type="button" onClick={()=>void save.run(()=>data.adjustStock(item.id,-1),'Baixa registrada.')} disabled={item.quantity<1||save.busy} aria-label={`Retirar uma unidade de ${item.name}`}>−</button><span>uma unidade</span><button type="button" onClick={()=>void save.run(()=>data.adjustStock(item.id,1),'Entrada registrada.')} disabled={save.busy} aria-label={`Adicionar uma unidade de ${item.name}`}>+</button><button className="text-button" onClick={()=>open(item)}>Editar</button></>}{!detailId&&<Link to={filters.href(`/estoque/${item.id}`)}>Ver ficha →</Link>}</div>{detailId&&<><DetailList items={[["Avisar quando chegar a",`${quantity(item.minimum)} ${item.unit}`],["Custo unitário estimado",data.canRead('financeEntries')?currency(item.unitCost):'Acesso restrito'],["Meio usual de compra",data.canRead('financeEntries')?item.paymentMethod:'Acesso restrito']]} />{item.notes&&<p className="detail-notes">{item.notes}</p>}</>}</article>)}</div>:<Empty>{detailId?'Material não encontrado.':filters.query||filters.params.get('low')?'Nenhum material corresponde aos filtros.':'Adicione o primeiro material da arena.'}</Empty>}
    {shown.some(item=>item.movements?.length)&&<section className="operation-card"><h2>{detailId?'Histórico de movimentos':'Movimentações recentes'}</h2><div className="movement-list">{shown.flatMap(item=>(item.movements??[]).map(movement=>({...movement,itemName:item.name,unit:item.unit,itemId:item.id}))).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)).slice(0,detailId?undefined:8).map(movement=><div className="movement-row" key={movement.id}><strong>{movement.kind}</strong><Link to={filters.href(`/estoque/${movement.itemId}`)}>{movement.itemName}</Link><small>{quantity(movement.quantity)} {movement.unit} · {displayDate(movement.occurredAt)}</small></div>)}</div></section>}
  </main>
}

const blankProject=():Omit<ArenaProject,'id'>=>({name:'',description:'',status:'Planejado',startDate:'',dueDate:'',owner:'',estimatedCost:0,actualCost:0,tasks:[],notes:''})
export function ProjectsPage(){return <ProjectsView />}
export function ProjectDetailsPage(){const{projectId}=useParams();return <ProjectsView detailId={projectId} />}
function ProjectsView({detailId}:{detailId?:string}){
  const data=useOperations();const filters=useFilters();const navigate=useNavigate();const save=useSave();const draftId=useRef(crypto.randomUUID());const existing=data.projects.find(item=>item.id===detailId)
  const[form,setForm]=useState<Omit<ArenaProject,'id'>|null>(null);const[editId,setEditId]=useState<string|undefined>()
  const open=(project?:ArenaProject)=>{draftId.current=crypto.randomUUID();setEditId(project?.id);setForm(project?{...project,tasks:[...project.tasks]}:blankProject())}
  async function submit(event:FormEvent){event.preventDefault();if(!form)return;const id=await save.run(()=>data.saveProject(form,editId??draftId.current));if(id){setForm(null);setEditId(undefined)}}
  if(!data.canRead('projects'))return <NoAccess />
  const overdue=(project:ArenaProject)=>Boolean(project.dueDate&&project.dueDate<today()&&!['Concluído','Cancelado'].includes(project.status))
  const filtered=data.projects.filter(project=>`${project.name} ${project.owner}`.toLocaleLowerCase('pt-BR').includes(filters.query.toLocaleLowerCase('pt-BR'))&&(!filters.status||project.status===filters.status)&&(filters.params.get('overdue')!=='1'||overdue(project)))
  return <main className="operation-page arena-page">{detailId&&<Breadcrumb to={filters.href('/projetos')} label="Projetos" />}<Heading title={detailId?existing?.name??'Ficha do projeto':'Projetos'} description="Acompanhe responsáveis, prazos, tarefas e os custos anotados de cada iniciativa." action={data.canWrite('projects')&&<button className="primary-link" onClick={()=>open(existing)}>{detailId?'Editar projeto':'+ Novo projeto'}</button>} /><Feedback action={save} />
    {form&&<form className="operation-card operation-form" onSubmit={submit}><Group title="1. Objetivo e responsável"><Field label="Nome do projeto" required value={form.name} onChange={v=>setForm({...form,name:v})} /><Field label="Responsável" value={form.owner} onChange={v=>setForm({...form,owner:v})} /><Field label="Situação" value={form.status} onChange={v=>setForm({...form,status:v})} options={['Planejado','Em andamento','Pausado','Concluído','Cancelado']} /><Notes label="Descrição e objetivo" value={form.description} onChange={v=>setForm({...form,description:v})} /></Group><Group title="2. Prazo e custos"><Field label="Início" type="date" value={form.startDate} onChange={v=>setForm({...form,startDate:v})} /><Field label="Prazo" type="date" value={form.dueDate} onChange={v=>setForm({...form,dueDate:v})} />{data.canWrite('financeEntries')&&<><Field label="Custo previsto (R$)" type="number" min={0} value={form.estimatedCost} onChange={v=>setForm({...form,estimatedCost:Number(v)})} /><Field label="Custo realizado (R$)" type="number" min={0} value={form.actualCost} onChange={v=>setForm({...form,actualCost:Number(v)})} /></>}</Group><Group title="3. Planejamento"><div className="arena-task-editor operation-field-wide"><p className="arena-hint">Cada tarefa tem seu próprio título e situação.</p>{form.tasks.map((task,index)=><div className="arena-task-editor-row" key={task.id}><Field label={`Tarefa ${index+1}`} required value={task.title} onChange={title=>setForm({...form,tasks:form.tasks.map(item=>item.id===task.id?{...item,title}:item)})} /><label className="arena-task-done"><input type="checkbox" aria-label={`Concluir tarefa ${index+1}`} checked={task.done} onChange={event=>setForm({...form,tasks:form.tasks.map(item=>item.id===task.id?{...item,done:event.target.checked}:item)})} />Concluída</label><button className="secondary-link" type="button" aria-label={`Remover tarefa ${index+1}`} onClick={()=>setForm({...form,tasks:form.tasks.filter(item=>item.id!==task.id)})}>Remover</button></div>)}<button className="secondary-link" type="button" onClick={()=>setForm({...form,tasks:[...form.tasks,{id:crypto.randomUUID(),title:'',done:false}]})}>+ Adicionar tarefa</button></div><Notes label="Notas e decisões" value={form.notes} onChange={v=>setForm({...form,notes:v})} /></Group><SaveRow busy={save.busy} onCancel={()=>setForm(null)} label="Salvar projeto" /></form>}
    {detailId?existing&&!form?<section className="operation-card project-detail"><Status warning={overdue(existing)}>{overdue(existing)?'Prazo vencido':existing.status}</Status><h2>Objetivo do projeto</h2><p>{existing.description||'Sem descrição adicionada.'}</p><DetailList items={[["Responsável",existing.owner],["Início",displayDate(existing.startDate)],["Prazo",displayDate(existing.dueDate)],["Custo previsto",data.canRead('financeEntries')?currency(existing.estimatedCost):'Acesso restrito'],["Custo realizado anotado",data.canRead('financeEntries')?currency(existing.actualCost):'Acesso restrito']]} /><p className="arena-hint">Custos anotados não representam pagamentos. Os lançamentos financeiros têm registros separados.</p><h3>Tarefas</h3>{existing.tasks.length?<ul className="arena-project-tasks">{existing.tasks.map(task=><li key={task.id}><label><input type="checkbox" checked={task.done} disabled={!data.canWrite('projects')||save.busy} onChange={()=>void save.run(()=>data.saveProject({...existing,tasks:existing.tasks.map(item=>item.id===task.id?{...item,done:!item.done}:item)},existing.id),'Tarefa atualizada.')} />{task.title}</label></li>)}</ul>:<p>Nenhuma tarefa anotada.</p>}{existing.notes&&<p className="detail-notes">{existing.notes}</p>}</section>:!existing?<Empty>{data.persistenceStatus==='connecting'?'Carregando projeto…':'Projeto não encontrado.'}</Empty>:null:<><div className="arena-toolbar"><Search filters={filters} /><Field label="Situação" value={filters.status} onChange={v=>filters.set('status',v)} options={[{value:'',label:'Todos'},'Planejado','Em andamento','Pausado','Concluído','Cancelado']} /><Field label="Prazo" value={filters.params.get('overdue')??''} onChange={v=>filters.set('overdue',v)} options={[{value:'',label:'Todos os prazos'},{value:'1',label:'Prazo vencido'}]} /></div><ListSummary count={filtered.length} label="projetos" />{filtered.length?<Pagination total={filtered.length}>{(start,end)=><div className="project-grid">{filtered.slice(start,end).map(project=><button className="project-card" key={project.id} onClick={()=>navigate(filters.href(`/projetos/${project.id}`))}><span className="project-card-top"><Status warning={overdue(project)}>{overdue(project)?'Prazo vencido':project.status}</Status><span aria-hidden="true">›</span></span><h2>{project.name}</h2><p>{project.description||'Sem descrição.'}</p><div className="project-card-footer"><span>{project.owner||'Responsável não definido'} · {displayDate(project.dueDate)}</span><strong>{project.tasks.filter(task=>task.done).length}/{project.tasks.length} tarefas</strong></div></button>)}</div>}</Pagination>:<Empty>Registre iniciativas para acompanhar prazo, tarefas e custos.</Empty>}</>}
  </main>
}
