import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useOperations, type ArenaProject, type InventoryItem, type Student, type TeamMember } from '../features/operations/DemoDataProvider'

function Heading({ eyebrow = 'Operação', title, description, action }: { eyebrow?: string; title: string; description: string; action?: ReactNode }) {
  return <header className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</header>
}
function Field({ label, value, onChange, type = 'text', required = false, min, options, placeholder }: {
  label: string; value: string | number; onChange: (value: string) => void; type?: string; required?: boolean
  min?: number; options?: string[]; placeholder?: string
}) {
  return <label className="operation-field">{label}{options ? <select value={value} required={required} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select> : <input value={value} type={type} required={required} min={min} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} />}</label>
}
function NoteField({ label, value, onChange, rows = 3 }: { label: string; value: string; onChange: (value: string) => void; rows?: number }) {
  return <label className="operation-field operation-field-wide">{label}<textarea value={value} rows={rows} onChange={(event) => onChange(event.target.value)} /></label>
}
function SaveRow({ onCancel, label = 'Salvar cadastro' }: { onCancel?: () => void; label?: string }) {
  return <div className="form-actions"><button className="primary-button" type="submit">{label}</button>{onCancel && <button className="secondary-link" type="button" onClick={onCancel}>Cancelar</button>}</div>
}
function Search({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  return <label className="search-box"><span aria-hidden="true">⌕</span><input aria-label="Buscar" placeholder="Buscar pelo nome..." value={value} onChange={(event) => onChange(event.target.value)} /></label>
}
function Empty({ children }: { children: ReactNode }) { return <div className="empty-state"><span>◎</span><p>{children}</p></div> }
const blankStudent = (): Omit<Student, 'id'> => ({ name: '', phone: '', birthDate: '', address: '', shirtSize: '', shortsSize: '', weeklyClasses: '1', days: '', class1: '', class2: '', monthlyAmount: 0, paymentStatus: 'A confirmar', paymentDate: '', statementName: '', status: 'A confirmar', notes: '' })

export function StudentsPage() {
  const { students } = useOperations(); const [query, setQuery] = useState('')
  const filtered = students.filter((student) => student.name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')))
  return <main className="operation-page"><Heading title="Alunos" description="Cadastros e detalhes de aula baseados nos campos da planilha de alunos." action={<Link className="primary-link" to="/alunos/novo">+ Adicionar aluno</Link>} />
    <div className="summary-row"><div><strong>{students.length}</strong><span>cadastros</span></div><div><strong>{students.filter((student) => student.status === 'Ativo').length}</strong><span>ativos</span></div><div><strong>{students.filter((student) => student.paymentStatus === 'Pago').length}</strong><span>pagamentos marcados como pagos</span></div></div>
    <div className="list-toolbar"><Search value={query} onChange={setQuery} /><span>Nome, aulas e pagamento</span></div>
    {filtered.length ? <div className="record-list">{filtered.map((student) => <Link className="record-row" to={`/alunos/${student.id}`} key={student.id}><span className="record-avatar">{student.name.slice(0, 1).toUpperCase()}</span><span className="record-main"><strong>{student.name}</strong><small>{student.weeklyClasses}x por semana · {student.days || 'Horário a definir'}</small></span><span className={`status-pill ${student.status === 'Ativo' ? 'is-active' : ''}`}>{student.status}</span><span className="row-arrow">›</span></Link>)}</div> : <Empty>{query ? 'Nenhum aluno corresponde à busca.' : 'Ainda não há alunos cadastrados. Adicione um aluno para começar.'}</Empty>}
  </main>
}

export function StudentDetailsPage() {
  const { studentId } = useParams(); const navigate = useNavigate(); const { students, saveStudent } = useOperations()
  const existing = students.find((student) => student.id === studentId); const isNew = studentId === 'novo'
  const [editing, setEditing] = useState(isNew || !existing); const [form, setForm] = useState<Omit<Student, 'id'>>(() => existing ? { ...existing } : blankStudent())
  useEffect(() => { if (existing && !isNew) { setForm({ ...existing }); setEditing(false) } }, [studentId, existing, isNew])
  const update = (key: keyof Omit<Student, 'id'>, value: string) => setForm((current) => ({ ...current, [key]: ['monthlyAmount'].includes(key) ? Number(value) : value }))
  function submit(event: FormEvent) { event.preventDefault(); const id = saveStudent(form, isNew ? undefined : studentId); navigate(`/alunos/${id}`) }
  if (!isNew && !existing) return <main className="operation-page"><Empty>Não encontramos esse cadastro.</Empty><Link className="secondary-link" to="/alunos">Voltar aos alunos</Link></main>
  return <main className="operation-page"><div className="breadcrumb"><Link to="/alunos">← Alunos</Link><span>/</span><span>{isNew ? 'Novo cadastro' : existing?.name}</span></div>
    <Heading eyebrow={isNew ? 'Novo cadastro' : 'Ficha do aluno'} title={isNew ? 'Adicionar aluno' : existing!.name} description={isNew ? 'Preencha os dados que vocês já controlam. Os campos pessoais podem ser completados depois.' : 'Dados pessoais, frequência e referência de pagamentos.'} action={!editing && <button className="secondary-link" onClick={() => setEditing(true)}>Editar dados</button>} />
    {editing ? <form className="operation-card operation-form" onSubmit={submit}><h2>Dados do aluno</h2><div className="field-grid">
      <Field label="Nome" required value={form.name} onChange={(v) => update('name', v)} placeholder="Nome como aparece no controle" />
      <Field label="Telefone" value={form.phone} onChange={(v) => update('phone', v)} type="tel" />
      <Field label="Data de nascimento" value={form.birthDate} onChange={(v) => update('birthDate', v)} type="date" />
      <Field label="Endereço" value={form.address} onChange={(v) => update('address', v)} />
      <Field label="Aulas por semana" value={form.weeklyClasses} onChange={(v) => update('weeklyClasses', v)} type="number" min={0} />
      <Field label="Dias da semana" value={form.days} onChange={(v) => update('days', v)} placeholder="Ex.: Segunda-feira / Sábado" />
      <Field label="Turma ou horário 1" value={form.class1} onChange={(v) => update('class1', v)} placeholder="Ex.: 19:00 até 20:00" />
      <Field label="Turma ou horário 2" value={form.class2} onChange={(v) => update('class2', v)} placeholder="Opcional" />
      <Field label="Valor mensal (R$)" value={form.monthlyAmount} onChange={(v) => update('monthlyAmount', v)} type="number" min={0} />
      <Field label="Status do pagamento" value={form.paymentStatus} onChange={(v) => update('paymentStatus', v)} options={['A confirmar', 'Pago', 'Pendente', 'Isento', 'Desistiu']} />
      <Field label="Data do pagamento" value={form.paymentDate} onChange={(v) => update('paymentDate', v)} type="date" />
      <Field label="Nome no extrato" value={form.statementName} onChange={(v) => update('statementName', v)} />
      <Field label="Tamanho de camiseta" value={form.shirtSize} onChange={(v) => update('shirtSize', v)} />
      <Field label="Tamanho de bermuda" value={form.shortsSize} onChange={(v) => update('shortsSize', v)} />
      <Field label="Situação" value={form.status} onChange={(v) => update('status', v)} options={['A confirmar', 'Ativo', 'Pausado', 'Inativo']} />
      <NoteField label="Observações" value={form.notes} onChange={(v) => update('notes', v)} />
    </div><SaveRow onCancel={!isNew ? () => setEditing(false) : undefined} /></form> : <>
      <div className="detail-grid"><section className="operation-card"><h2>Aulas e pagamentos</h2><dl className="detail-list"><div><dt>Frequência</dt><dd>{existing!.weeklyClasses}x por semana</dd></div><div><dt>Dias</dt><dd>{existing!.days || 'Não informado'}</dd></div><div><dt>Turma 1</dt><dd>{existing!.class1 || 'Não informado'}</dd></div><div><dt>Turma 2</dt><dd>{existing!.class2 || 'Não informado'}</dd></div><div><dt>Mensalidade anotada</dt><dd>{currency(existing!.monthlyAmount)}</dd></div><div><dt>Último status de pagamento</dt><dd><span className="status-pill">{existing!.paymentStatus}</span></dd></div><div><dt>Data de pagamento</dt><dd>{displayDate(existing!.paymentDate)}</dd></div><div><dt>Nome no extrato</dt><dd>{existing!.statementName || 'Não informado'}</dd></div></dl></section>
      <section className="operation-card"><h2>Dados pessoais</h2><dl className="detail-list"><div><dt>Telefone</dt><dd>{existing!.phone || 'Não informado'}</dd></div><div><dt>Nascimento</dt><dd>{displayDate(existing!.birthDate)}</dd></div><div><dt>Endereço</dt><dd>{existing!.address || 'Não informado'}</dd></div><div><dt>Camiseta</dt><dd>{existing!.shirtSize || 'Não informado'}</dd></div><div><dt>Bermuda</dt><dd>{existing!.shortsSize || 'Não informado'}</dd></div><div><dt>Situação</dt><dd>{existing!.status}</dd></div></dl>{existing!.notes && <p className="detail-notes">{existing!.notes}</p>}</section></div>
    </>}
  </main>
}

const blankTeam = (): Omit<TeamMember, 'id'> => ({ name: '', phone: '', role: 'Professor de futevôlei', payAmount: 0, payBasis: 'Por hora', paymentFrequency: 'Semanal', paymentDay: '', status: 'Ativo', notes: '' })
export function TeamPage() {
  const { team, saveTeamMember } = useOperations(); const [form, setForm] = useState<Omit<TeamMember, 'id'> | null>(null); const [editId, setEditId] = useState<string | undefined>(); const [query, setQuery] = useState('')
  function submit(event: FormEvent) { event.preventDefault(); if (form) saveTeamMember(form, editId); setForm(null); setEditId(undefined) }
  const filtered = team.filter((member) => `${member.name} ${member.role}`.toLowerCase().includes(query.toLowerCase()))
  return <main className="operation-page"><Heading title="Equipe" description="Pessoas, funções e acordos de pagamento registrados pela arena." action={<button className="primary-link" onClick={() => { setEditId(undefined); setForm(blankTeam()) }}>+ Adicionar pessoa</button>} />
    <div className="summary-row"><div><strong>{team.length}</strong><span>pessoas cadastradas</span></div><div><strong>{team.filter((person) => person.status === 'Ativo').length}</strong><span>ativas</span></div></div>
    {form && <form className="operation-card operation-form" onSubmit={submit}><h2>{editId ? "Editar cadastro de equipe" : "Novo cadastro de equipe"}</h2><div className="field-grid"><Field label="Nome" required value={form.name} onChange={(v) => setForm({ ...form, name: v })} /><Field label="Telefone" type="tel" value={form.phone} onChange={(v) => setForm({ ...form, phone: v })} /><Field label="Função" value={form.role} onChange={(v) => setForm({ ...form, role: v })} options={['Professor de futevôlei', 'Bar', 'Limpeza', 'Apoio operacional', 'Outra']} /><Field label="Valor combinado (R$)" type="number" min={0} value={form.payAmount} onChange={(v) => setForm({ ...form, payAmount: Number(v) })} /><Field label="Base do valor" value={form.payBasis} onChange={(v) => setForm({ ...form, payBasis: v })} options={['Por hora', 'Por dia', 'Por turno', 'Por aula', 'Valor mensal', 'Outro']} /><Field label="Frequência de pagamento" value={form.paymentFrequency} onChange={(v) => setForm({ ...form, paymentFrequency: v })} options={['A combinar', 'Diário', 'Semanal', 'Quinzenal', 'Mensal']} /><Field label="Dia combinado para pagar" value={form.paymentDay} onChange={(v) => setForm({ ...form, paymentDay: v })} placeholder="Ex.: toda sexta-feira" /><Field label="Situação" value={form.status} onChange={(v) => setForm({ ...form, status: v })} options={['Ativo', 'A confirmar', 'Inativo']} /><NoteField label="Observações do acordo" value={form.notes} onChange={(v) => setForm({ ...form, notes: v })} /></div><SaveRow onCancel={() => { setForm(null); setEditId(undefined) }} /></form>}
    <div className="list-toolbar"><Search value={query} onChange={setQuery} /></div>{filtered.length ? <div className="record-list">{filtered.map((person) => <article className="record-row" key={person.id}><span className="record-avatar gold-avatar">{person.name.slice(0, 1).toUpperCase()}</span><span className="record-main"><strong>{person.name}</strong><small>{person.role} · {person.payBasis} · pagamento {person.paymentFrequency.toLowerCase()}</small></span><span className="status-pill">{person.status}</span><span className="pay-summary">{currency(person.payAmount)}</span><button className="text-button" type="button" onClick={() => { setEditId(person.id); setForm({ ...person }) }}>Editar</button></article>)}</div> : <Empty>{query ? 'Nenhum resultado.' : 'Cadastre professores, equipe do bar, limpeza e apoio operacional.'}</Empty>}
  </main>
}

const blankInventory = (): Omit<InventoryItem, 'id'> => ({ name: '', category: 'Limpeza', unit: 'unidade', quantity: 0, minimum: 0, unitCost: 0, location: '', notes: '', paymentMethod: 'A definir', movements: [] })
export function InventoryPage() {
  const { inventory, saveInventoryItem, adjustStock } = useOperations(); const [form, setForm] = useState<Omit<InventoryItem, 'id'> | null>(null); const [editId, setEditId] = useState<string | undefined>(); const [query, setQuery] = useState('')
  function submit(event: FormEvent) { event.preventDefault(); if (form) saveInventoryItem(form, editId); setForm(null); setEditId(undefined) }
  const filtered = inventory.filter((item) => `${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase()))
  const lowStock = inventory.filter((item) => item.quantity <= item.minimum).length
  return <main className="operation-page"><Heading title="Estoque" description="Acompanhe materiais esportivos, produtos de limpeza e os itens do bar." action={<button className="primary-link" onClick={() => { setEditId(undefined); setForm(blankInventory()) }}>+ Adicionar item</button>} />
    <div className="summary-row"><div><strong>{inventory.length}</strong><span>itens</span></div><div><strong>{lowStock}</strong><span>no mínimo ou abaixo</span></div><div><strong>{inventory.filter((item) => item.category === 'Bar').length}</strong><span>itens do bar</span></div></div>
    <aside className="info-banner"><strong>Bar e PagBank</strong><span>Cadastre itens do bar e anote o meio de pagamento nas observações. A integração com a PagBank ainda será definida; este controle não consulta vendas nem saldo da conta.</span></aside>
    {form && <form className="operation-card operation-form" onSubmit={submit}><h2>{editId ? 'Editar item' : 'Novo item'}</h2><div className="field-grid"><Field label="Produto ou material" required value={form.name} onChange={(v) => setForm({ ...form, name: v })} /><Field label="Área" value={form.category} onChange={(v) => setForm({ ...form, category: v })} options={['Limpeza', 'Bar', 'Material esportivo', 'Equipamento de ginástica', 'Administrativo', 'Outro']} /><Field label="Unidade" value={form.unit} onChange={(v) => setForm({ ...form, unit: v })} options={['unidade', 'pacote', 'caixa', 'lata', 'garrafa', 'kg', 'litro', 'par']} /><Field label="Quantidade atual" type="number" min={0} value={form.quantity} onChange={(v) => setForm({ ...form, quantity: Number(v) })} /><Field label="Avisar quando chegar a" type="number" min={0} value={form.minimum} onChange={(v) => setForm({ ...form, minimum: Number(v) })} /><Field label="Custo unitário estimado (R$)" type="number" min={0} value={form.unitCost} onChange={(v) => setForm({ ...form, unitCost: Number(v) })} /><Field label="Onde fica guardado" value={form.location} onChange={(v) => setForm({ ...form, location: v })} /><Field label="Meio usual de compra" value={form.paymentMethod} onChange={(v) => setForm({ ...form, paymentMethod: v })} options={['A definir', 'PagBank', 'Pix', 'Dinheiro', 'Cartão', 'Outro']} /><NoteField label="Observações" value={form.notes} onChange={(v) => setForm({ ...form, notes: v })} /></div><SaveRow onCancel={() => { setForm(null); setEditId(undefined) }} /></form>}
    <div className="list-toolbar"><Search value={query} onChange={setQuery} /><span>Quantidade abaixo do mínimo fica destacada</span></div>{filtered.length ? <div className="inventory-grid">{filtered.map((item) => <article className={`inventory-card ${item.quantity <= item.minimum ? 'is-low' : ''}`} key={item.id}><div className="inventory-title"><div><span className="eyebrow">{item.category}</span><h2>{item.name}</h2></div><span className="stock-number">{fmt(item.quantity)} <small>{item.unit}</small></span></div><p>{item.location || 'Local não definido'}{item.quantity <= item.minimum && <strong className="low-stock"> · Repor estoque</strong>}</p><div className="stock-controls"><button type="button" onClick={() => adjustStock(item.id, -1)} disabled={item.quantity <= 0} aria-label={`Retirar uma unidade de ${item.name}`}>−</button><span>ajustar quantidade</span><button type="button" onClick={() => adjustStock(item.id, 1)} aria-label={`Adicionar uma unidade de ${item.name}`}>+</button><button className="text-button" type="button" onClick={() => { setEditId(item.id); setForm({ ...item, movements: item.movements ?? [] }) }}>Editar</button></div></article>)}</div> : <Empty>{query ? 'Nenhum item encontrado.' : 'Adicione bolas, cones, produtos de limpeza, itens do bar e outros materiais da arena.'}</Empty>}
    {inventory.some((item) => item.movements?.length) && <section className="operation-card"><h2>Movimentações recentes</h2><div className="movement-list">{inventory.flatMap((item) => (item.movements ?? []).map((movement) => ({ ...movement, itemName: item.name, unit: item.unit }))).sort((left, right) => right.occurredAt.localeCompare(left.occurredAt)).slice(0, 8).map((movement) => <div className="movement-row" key={movement.id}><strong className={movement.kind === 'Entrada' ? 'movement-in' : 'movement-out'}>{movement.kind}</strong><span>{movement.itemName}</span><small>{fmt(movement.quantity)} {movement.unit} · {displayDate(movement.occurredAt.slice(0, 10))}</small></div>)}</div></section>}
  </main>
}

const blankProject = (): Omit<ArenaProject, 'id'> => ({ name: '', description: '', status: 'Planejado', startDate: '', dueDate: '', owner: '', estimatedCost: 0, actualCost: 0, tasks: [], notes: '' })
export function ProjectsPage() {
  const { projects, saveProject } = useOperations(); const [form, setForm] = useState<Omit<ArenaProject, 'id'> | null>(null); const [selectedId, setSelectedId] = useState<string | null>(null)
  const selected = projects.find((project) => project.id === selectedId)
  function submit(event: FormEvent) { event.preventDefault(); if (form) saveProject(form, selectedId ?? undefined); setForm(null); setSelectedId(null) }
  const edit = (project: ArenaProject) => { setSelectedId(project.id); setForm({ ...project, tasks: [...project.tasks] }) }
  return <main className="operation-page"><Heading title="Projetos" description="Planejamento, prazos, responsáveis, tarefas e custos estimados e realizados." action={<button className="primary-link" onClick={() => { setSelectedId(null); setForm(blankProject()) }}>+ Novo projeto</button>} />
    <div className="summary-row"><div><strong>{projects.length}</strong><span>projetos registrados</span></div><div><strong>{projects.filter((project) => project.status === 'Em andamento').length}</strong><span>em andamento</span></div><div><strong>{currency(projects.reduce((total, project) => total + project.actualCost, 0))}</strong><span>custo realizado anotado</span></div></div>
    {form && <form className="operation-card operation-form" onSubmit={submit}><h2>{selectedId ? 'Editar projeto' : 'Novo projeto'}</h2><div className="field-grid"><Field label="Nome do projeto" required value={form.name} onChange={(v) => setForm({ ...form, name: v })} /><Field label="Situação" value={form.status} onChange={(v) => setForm({ ...form, status: v })} options={['Planejado', 'Em andamento', 'Pausado', 'Concluído', 'Cancelado']} /><Field label="Início" type="date" value={form.startDate} onChange={(v) => setForm({ ...form, startDate: v })} /><Field label="Prazo" type="date" value={form.dueDate} onChange={(v) => setForm({ ...form, dueDate: v })} /><Field label="Responsável" value={form.owner} onChange={(v) => setForm({ ...form, owner: v })} /><Field label="Custo previsto (R$)" type="number" min={0} value={form.estimatedCost} onChange={(v) => setForm({ ...form, estimatedCost: Number(v) })} /><Field label="Custo realizado (R$)" type="number" min={0} value={form.actualCost} onChange={(v) => setForm({ ...form, actualCost: Number(v) })} /><NoteField label="Descrição e objetivo" value={form.description} onChange={(v) => setForm({ ...form, description: v })} /><NoteField label="Tarefas (uma por linha)" value={form.tasks.map((task) => `${task.done ? '[x]' : '[ ]'} ${task.title}`).join('\n')} onChange={(v) => setForm({ ...form, tasks: v.split('\n').filter(Boolean).map((line) => ({ id: line, title: line.replace(/^\[[ x]\]\s*/, ''), done: /^\[x\]/i.test(line) })) })} /><NoteField label="Notas e decisões" value={form.notes} onChange={(v) => setForm({ ...form, notes: v })} /></div><SaveRow onCancel={() => setForm(null)} label="Salvar projeto" /></form>}
    {selected && !form && <section className="operation-card project-detail"><div className="project-detail-head"><div><span className="status-pill">{selected.status}</span><h2>{selected.name}</h2><p>{selected.description || 'Sem descrição adicionada.'}</p></div><button className="secondary-link" onClick={() => edit(selected)}>Editar projeto</button></div><div className="project-metrics"><div><small>Prazo</small><strong>{displayDate(selected.dueDate)}</strong></div><div><small>Responsável</small><strong>{selected.owner || 'Não definido'}</strong></div><div><small>Previsto</small><strong>{currency(selected.estimatedCost)}</strong></div><div><small>Realizado</small><strong>{currency(selected.actualCost)}</strong></div></div><h3>Planejamento</h3>{selected.tasks.length ? <ul className="task-list">{selected.tasks.map((task) => <li key={task.id}>{task.done ? '✓' : '○'} {task.title}</li>)}</ul> : <p className="muted-copy">Nenhuma tarefa anotada.</p>}{selected.notes && <p className="detail-notes">{selected.notes}</p>}</section>}
    <div className="project-grid">{projects.map((project) => <button className="project-card" key={project.id} onClick={() => { setSelectedId(project.id); setForm(null) }}><span className="project-card-top"><span className="status-pill">{project.status}</span><span>›</span></span><h2>{project.name}</h2><p>{project.description || 'Sem descrição.'}</p><div className="project-card-footer"><span>Prazo {displayDate(project.dueDate)}</span><strong>{currency(project.actualCost)} / {currency(project.estimatedCost)}</strong></div></button>)}</div>
    {!projects.length && !form && <Empty>Registre iniciativas da arena para acompanhar prazo, tarefas e custos.</Empty>}
  </main>
}

function currency(value: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number.isFinite(value) ? value : 0) }
function fmt(value: number) { return new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 2 }).format(value) }
function displayDate(value: string) { if (!value) return 'Não informado'; const date = new Date(`${value}T00:00:00`); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat('pt-BR').format(date) }
