import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { apiFetch } from '../lib/http'
import { useAuth } from '../features/auth/authContext'
import { useOperations } from '../features/operations/DemoDataProvider'
import type { RentalBar, RentalGroup } from '../features/arena/rentals'
import type { Reservation } from '../features/arena/types'
import { Feedback, Field, currency, displayDate, useSave } from './arenaUi'
type TabChoice = { id: string; number: number; name: string; state: string }
export function RentalBarPanel({ group, meetings, links, onLinked }: { group: RentalGroup; meetings: Reservation[]; links: RentalBar[]; onLinked: () => Promise<void> }) {
  const { user } = useAuth(); const data = useOperations(); const action = useSave(); const [search, setSearch] = useState(''); const [query, setQuery] = useState<string | null>(null); const [page, setPage] = useState(1); const [meetingId, setMeeting] = useState(''); const [memberId, setMember] = useState('')
  const canLink = data.canWrite('rentalGroups') && Boolean(user?.roles.includes('Owner') || user?.permissions.includes('bar:sales:operate') && user?.permissions.includes('bar:sales:read'))
  const selected = meetings.find(r => r.id === meetingId && r.status !== 'Cancelada')?.id ?? meetings.find(r => r.status !== 'Cancelada')?.id ?? ''
  const choices = useQuery({ queryKey: ['rental-tab-search', query, page], queryFn: () => apiFetch<{ items: TabChoice[]; total: number }>(`/api/v1/bar/tabs?search=${encodeURIComponent(query ?? '')}&page=${page}&pageSize=10`), enabled: canLink && query !== null })
  async function link(tabId: string) { await action.run(async () => { const previous = links.find(l => l.tabId === tabId); await apiFetch(`/api/v1/rentals/groups/${group.id}/bar/${tabId}`, { method: 'PUT', body: JSON.stringify({ reservationId: selected, memberId: memberId || null, version: previous?.version ?? 0 }) }); await onLinked() }, 'Comanda vinculada ao encontro.') }
  return <><Feedback action={action} />{links.length > 0 ? <div className="rental-bar-links">{links.map(row => <div className="rental-bar-row" key={row.tabId}><Link to={`/atendimento/comandas/${row.tabId}`}>Comanda #{row.number} · {row.name || 'Sem nome'} →</Link><span>{displayDate(meetings.find(r => r.id === row.reservationId)?.date)} · {row.memberId ? group.members.find(m => m.id === row.memberId)?.name : 'Turma'}</span><span>{currency(row.total)} consumo · {currency(row.paid)} recebido · {currency(row.due)} em aberto</span>{canLink && <button className="secondary-link" disabled={action.busy} onClick={() => void action.run(async () => { await apiFetch(`/api/v1/rentals/groups/${group.id}/bar/${row.tabId}?version=${row.version}`, { method: 'DELETE' }); await onLinked() }, 'Vínculo removido. A comanda e os pagamentos foram preservados.')}>Desvincular comanda #{row.number}</button>}</div>)}</div> : <p>Nenhuma comanda vinculada nesta competência.</p>}
    {canLink && selected && <details className="rental-linker"><summary>Vincular ou corrigir comanda do encontro</summary><p>Abra a comanda no atendimento como de costume. Depois, localize-a aqui e escolha o encontro e o integrante. Cada comanda pertence a um único grupo.</p><div className="field-grid"><Field label="Encontro da comanda" value={selected} onChange={setMeeting} options={meetings.filter(r => r.status !== 'Cancelada').map(r => ({ value: r.id, label: `${displayDate(r.date)} · ${r.startTime}` }))} /><Field label="Comanda de quem?" value={memberId} onChange={setMember} options={[{ value: '', label: 'Da turma / compartilhada' }, ...group.members.map(m => ({ value: m.id, label: m.name }))]} /></div><form className="arena-toolbar" onSubmit={e => { e.preventDefault(); setPage(1); setQuery(search.trim()) }}><Field label="Buscar comanda por nome ou número" value={search} onChange={setSearch} /><button className="secondary-link" type="submit">Buscar comandas</button><Link to="/atendimento/comandas">Abrir atendimento →</Link></form>{choices.error && <p role="alert">{choices.error.message}</p>}{choices.isFetching && <p>Buscando…</p>}{choices.data?.items.map(tab => <div key={tab.id} className="rental-tab-choice"><span>#{tab.number} · {tab.name || 'Sem nome'} · {tab.state === 'Open' ? 'Aberta' : 'Fechada'}</span><button className="secondary-link" disabled={action.busy} onClick={() => void link(tab.id)}>{links.some(l => l.tabId === tab.id) ? 'Atualizar vínculo' : 'Vincular'}</button></div>)}{choices.data && !choices.data.items.length && <p>Nenhuma comanda encontrada.</p>}{choices.data && <div className="arena-actions"><button className="secondary-link" disabled={page <= 1 || choices.isFetching} onClick={() => setPage(p => p - 1)}>Anterior</button><span>Página {page}</span><button className="secondary-link" disabled={page * 10 >= choices.data.total || choices.isFetching} onClick={() => setPage(p => p + 1)}>Próxima</button></div>}</details>}
  </>
}
