import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { apiFetch } from '../lib/http'
import { useAuth } from '../features/auth/authContext'
import { useOperations } from '../features/operations/DemoDataProvider'
import type { RentalGroup, RentalMember, RentalPreview, RentalBar } from '../features/arena/rentals'
import { weekDays, fifthPolicies } from '../features/arena/rentals'
import { Breadcrumb, DetailList, Empty, Feedback, Field, Group, Heading, Notes, Pagination, SaveRow, Search, Status, currency, displayDate, today, useFilters, useSave } from './arenaUi'
import { RentalBarPanel } from './RentalBarPanel'
import { ContextLink, Disclosure, EditorPanel, SectionTabs, useEditorQuery, useSection } from '../components/managementUi'
import './rental-groups.css'

function RentalStats({ items }: { items: [string, string][] }) { return <div className="rental-stats">{items.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div> }
export function RentalGroupsPage() {
  const data = useOperations(); const filters = useFilters(); const month = today().slice(0, 7)
  const groups = data.rentalGroups.filter(g => `${g.name} ${g.members.map(m => m.name).join(' ')}`.toLocaleLowerCase('pt-BR').includes(filters.query.toLocaleLowerCase('pt-BR')))
  const active = data.rentalGroups.filter(g => g.status === 'Ativo' && g.startDate <= today() && (!g.endDate || g.endDate >= today()))
  const loaded = data.dataUpdatedAt !== null
  return <main className="operation-page arena-page"><Heading eyebrow="Quadra · turmas da casa" title="Mensalistas" description="Conheça cada pessoa da turma. Cuide do horário fixo, dos encontros e da resenha depois do jogo." action={data.canWrite('rentalGroups') && <Link className="primary-link" to="/mensalistas/novo">Cadastrar grupo</Link>} /><Feedback />
    <RentalStats items={[["Grupos ativos", loaded ? String(active.length) : '…'], ['Integrantes ativos nos grupos', loaded ? String(active.reduce((n, g) => n + g.members.filter(m => m.status === 'Ativo').length, 0)) : '…'], ['Encontros neste mês', loaded ? String(data.reservations.filter(r => r.rentalGroupId && r.date.startsWith(month) && r.status !== 'Cancelada').length) : '…']]} />
    <Disclosure title="Como organizar as turmas">{data.canRead('financeEntries') && <Link to="/financeiro/historico?series=mensalistas">Consultar pagamentos históricos nas planilhas →</Link>}<h2>O grupo vai além do organizador</h2><p>Cadastre todos os integrantes, escolha um responsável e um suplente e confirme o acordo. Depois, revise os encontros do mês antes de reservar a quadra e lançar a mensalidade.</p><p>As comandas vinculadas permitem acompanhar o consumo do grupo, mesmo quando cada pessoa paga a sua conta.</p></Disclosure>
    <Search filters={filters} placeholder="Buscar grupo ou integrante…" />
    {groups.length === 0 ? <Empty>{data.rentalGroups.length ? 'Nenhum grupo corresponde à busca.' : 'Os grupos atuais ainda precisam ser cadastrados. Comece pelo nome da turma e pelos integrantes.'}</Empty> : <Pagination total={groups.length}>{(start,end)=><div className="rental-cards">{groups.slice(start,end).map(g => <Link className="rental-card" to={filters.href(`/mensalistas/${g.id}`)} key={g.id}><div><h2>{g.name}</h2><Status>{g.status}</Status></div><p>{weekDays[g.weekDay]} · {g.startTime} às {g.endTime}</p><p>{g.members.length ? `${g.members.filter(m => m.status === 'Ativo').length} integrantes cadastrados` : 'Integrantes a cadastrar'} · {g.sport || 'Modalidade a combinar'}</p><small>Responsável: {g.members.find(m => m.id === g.organizerId)?.name || 'A confirmar'}</small>{g.costsVisible !== false && data.canRead('financeEntries') && <strong>{currency(g.monthlyAmount)} / mês</strong>}<span>Ver turma e encontros →</span></Link>)}</div>}</Pagination>}
  </main>
}
function blankGroup(courtId: string): RentalGroup {
  const member: RentalMember = { id: crypto.randomUUID(), name: '', phone: '', status: 'Ativo' }
  return { id: '', name: '', sport: 'Futevôlei', courtId, weekDay: 1, startTime: '20:00', endTime: '22:00', startDate: today(), endDate: '', status: 'Ativo', capacity: null, organizerId: member.id, backupId: '', members: [member], monthlyAmount: null, dueDay: null, fifthPolicy: 'A confirmar', extraAmount: null, notes: '' }
}
function GroupEditor({ initial, cancel }: { initial: RentalGroup; cancel: () => void }) {
  const [value, setValue] = useState(initial); const data = useOperations(); const save = useSave(); const navigate = useNavigate()
  const set = <K extends keyof RentalGroup>(key: K, v: RentalGroup[K]) => setValue(old => ({ ...old, [key]: v }))
  const member = (id: string, update: Partial<RentalMember>) => setValue(old => ({ ...old, members: old.members.map(m => m.id === id ? { ...m, ...update } : m) }))
  const existingIds = new Set(initial.members.map(m => m.id)); const editMoney = data.canWrite('financeEntries')
  return <form className="operation-form" onSubmit={async e => { e.preventDefault(); const id = await save.run(() => data.saveRentalGroup({ ...value, name: value.name.trim(), members: value.members.filter(m => existingIds.has(m.id) && initial.id || m.name.trim() || m.phone.trim()).map(m => ({ ...m, name: m.name.trim() })), organizerId: value.members.some(m => m.id === value.organizerId && m.name.trim()) ? value.organizerId : '' }, value.id || undefined)); if (id) { if (value.id) cancel(); else navigate(`/mensalistas/${id}`) } }}><Feedback action={save} /><fieldset disabled={save.busy} className="rental-editor-fields">
    <Group title="Turma e acordo"><Field label="Nome do grupo" value={value.name} onChange={v => set('name', v)} required /><Field label="Modalidade" value={value.sport} onChange={v => set('sport', v)} /><Field label="Situação" value={value.status} onChange={v => set('status', v as RentalGroup['status'])} options={['Ativo', 'Pausado', 'Encerrado']} /><Field label="Integrantes previstos" type="number" min={1} max={50} step="1" value={value.capacity ?? ''} onChange={v => set('capacity', v === '' ? null : Number(v))} /><Field label="Início do acordo" type="date" value={value.startDate} onChange={v => set('startDate', v)} required /><Field label="Fim do acordo (opcional)" type="date" value={value.endDate} onChange={v => set('endDate', v)} /></Group>
    <Group title="Horário semanal"><Field label="Quadra" value={value.courtId} onChange={v => set('courtId', v)} required options={[{ value: '', label: 'Selecione' }, ...data.courts.map(c => ({ value: c.id, label: c.name }))]} /><Field label="Dia da semana" value={value.weekDay} onChange={v => set('weekDay', Number(v))} options={weekDays.map((label, index) => ({ label, value: String(index) }))} /><Field label="Início" type="time" value={value.startTime} onChange={v => set('startTime', v)} required /><Field label="Término" type="end-time" value={value.endTime} onChange={v => set('endTime', v)} required /></Group>
    <p className="arena-message">O cadastro guarda o acordo. A quadra só é reservada ao gerar e confirmar os encontros de cada mês. Alterar ou pausar o grupo não cancela encontros já gerados.</p>
    <Group title="Quem faz parte"><div className="operation-field-wide rental-members-editor">{value.members.map((m, index) => <div key={m.id} className="rental-member-edit"><Field label={`Integrante ${index + 1} · nome completo`} value={m.name} onChange={v => member(m.id, { name: v })} required={Boolean(initial.id && existingIds.has(m.id) || m.phone)} /><Field label={`Integrante ${index + 1} · telefone (opcional)`} value={m.phone} onChange={v => member(m.id, { phone: v })} type="tel" /><Field label={`Integrante ${index + 1} · situação`} value={m.status} onChange={v => member(m.id, { status: v as RentalMember['status'] })} options={['Ativo', 'Inativo']} />{(!initial.id || !existingIds.has(m.id)) && <button type="button" className="secondary-link" onClick={() => set('members', value.members.filter(row => row.id !== m.id))}>Remover integrante {index + 1}</button>}</div>)}<button type="button" className="secondary-link" disabled={value.members.length >= 50} onClick={() => set('members', [...value.members, { id: crypto.randomUUID(), name: '', phone: '', status: 'Ativo' }])}>+ Adicionar integrante</button></div><Field label="Responsável pelo grupo" value={value.organizerId} onChange={v => set('organizerId', v)} options={[{ value: '', label: 'A confirmar' }, ...value.members.filter(m => m.status === 'Ativo').map(m => ({ value: m.id, label: m.name || 'Preencha o nome' }))]} /><Field label="Suplente (opcional)" value={value.backupId} onChange={v => set('backupId', v)} options={[{ value: '', label: 'Sem suplente' }, ...value.members.filter(m => m.status === 'Ativo' && m.id !== value.organizerId).map(m => ({ value: m.id, label: m.name || 'Preencha o nome' }))]} /></Group>
    <Group title="Acordo financeiro">{data.canRead('financeEntries') && <Field label="Valor mensal do grupo (vazio = a combinar)" value={value.monthlyAmount ?? ''} onChange={v => set('monthlyAmount', v === '' ? null : Number(v))} type="number" min={0} step="0.01" disabled={!editMoney} />}<Field label="Dia do vencimento" value={value.dueDay ?? ''} onChange={v => set('dueDay', v === '' ? null : Number(v))} type="number" min={1} max={31} step="1" /><Field label="Quando houver um quinto encontro" value={value.fifthPolicy} onChange={v => set('fifthPolicy', v as RentalGroup['fifthPolicy'])} options={fifthPolicies} />{value.fifthPolicy === 'Extra' && data.canRead('financeEntries') && <Field label="Adicional pelo quinto encontro" value={value.extraAmount ?? ''} onChange={v => set('extraAmount', v === '' ? null : Number(v))} type="number" min={0} step="0.01" disabled={!editMoney} />}<Notes label="Combinados, feriados e reposições" value={value.notes} onChange={v => set('notes', v)} /></Group>
    <SaveRow busy={save.busy || data.saving} onCancel={cancel} label="Salvar grupo" />
  </fieldset></form>
}
export function RentalGroupPage() {
  const { groupId } = useParams(); const data = useOperations(); const navigate = useNavigate(); const [editing, setEditing] = useEditorQuery(false, groupId)
  const group = data.rentalGroups.find(g => g.id === groupId)
  if (groupId === 'novo') return <main className="operation-page arena-page"><Breadcrumb to="/mensalistas" label="Mensalistas" /><Heading title="Novo grupo mensalista" description="Cadastre cada integrante e o acordo semanal da turma." />{data.canWrite('rentalGroups') ? <EditorPanel title="Novo grupo mensalista" busy={data.saving} onClose={()=>navigate('/mensalistas')}><GroupEditor initial={blankGroup(data.courts[0]?.id ?? '')} cancel={() => navigate('/mensalistas')} /></EditorPanel> : <p>Apenas a gestão pode cadastrar grupos.</p>}</main>
  if (!group) return <main className="operation-page arena-page"><Breadcrumb to="/mensalistas" label="Mensalistas" /><Feedback /><p>{data.dataUpdatedAt ? 'Grupo não encontrado.' : 'Carregando grupo…'}</p></main>
  return <main className="operation-page arena-page"><Breadcrumb to="/mensalistas" label="Mensalistas" /><Heading title={group.name} description={`${weekDays[group.weekDay]} · ${group.startTime} às ${group.endTime} · ${group.sport}`} action={!editing && data.canWrite('rentalGroups') && <button className="secondary-link" onClick={() => setEditing(true)}>Editar grupo e integrantes</button>} /><Feedback />{editing && data.canWrite('rentalGroups') && <EditorPanel title="Editar grupo e integrantes" busy={data.saving} onClose={()=>setEditing(false)}><GroupEditor initial={group} cancel={() => setEditing(false)} /></EditorPanel>}<GroupDetails group={group} /></main>
}
function GroupDetails({ group }: { group: RentalGroup }) {
  const data = useOperations(); const { user } = useAuth(); const queryClient = useQueryClient(); const filters=useFilters(); const month=filters.params.get('month')??today().slice(0,7); const setMonth=(value:string)=>filters.set('month',value); const [charge, setCharge] = useState(false); const [selectedMeeting, setSelectedMeeting] = useState(''); const action = useSave()
  const owner = user?.roles.includes('Owner'); const canBar = Boolean(owner || user?.permissions.includes('bar:finance:read'))
  const tabs=[{value:'resumo',label:'Resumo'},{value:'integrantes',label:'Integrantes'},{value:'encontros',label:'Encontros e presença'},...(data.canRead('financeEntries')?[{value:'financeiro',label:'Financeiro'}]:[]),...(canBar?[{value:'bar',label:'Bar'}]:[])]
  const [section,setSection]=useSection(tabs.map(t=>t.value))
  const monthRow = data.rentalMonths.find(m => m.rentalGroupId === group.id && m.month === month)
  const meetings = data.reservations.filter(r => r.rentalGroupId === group.id && r.rentalMonth === month).sort((a, b) => a.date.localeCompare(b.date))
  const meeting = meetings.find(r => r.id === selectedMeeting) ?? meetings.find(r => r.date === today()) ?? meetings[0]
  const entries = data.financeEntries.filter(f => f.sourceKind === 'rentalMonths' && f.sourceId === monthRow?.id)
  const preview = useQuery({ queryKey: ['rental-preview', group.id, month, group.version], queryFn: () => apiFetch<RentalPreview>(`/api/v1/rentals/groups/${group.id}/months/${month}/preview`), enabled: section==='encontros' && !monthRow && /^\d{4}-\d{2}$/.test(month) && data.persistenceStatus === 'connected', refetchOnWindowFocus: true })
  const bar = useQuery({ queryKey: ['rental-bar', group.id, month], queryFn: () => apiFetch<RentalBar[]>(`/api/v1/rentals/groups/${group.id}/bar?month=${month}`), enabled: canBar && section==='bar' && /^\d{4}-\d{2}$/.test(month) && data.persistenceStatus === 'connected', refetchInterval: 30000 })
  const members = [...(monthRow?.members ?? []), ...group.members.filter(m => m.status === 'Ativo' && !monthRow?.members.some(old => old.id === m.id))]
  const finance = data.canRead('financeEntries'); const liveEntry = entries.find(f => f.status !== 'Cancelado')
  const amounts = bar.data?.reduce((acc, row) => ({ total: acc.total + row.total, paid: acc.paid + row.paid, due: acc.due + row.due }), { total: 0, paid: 0, due: 0 })
  async function generate() { await action.run(async () => { await apiFetch(`/api/v1/rentals/groups/${group.id}/months`, { method: 'POST', body: JSON.stringify({ month, groupVersion: preview.data!.groupVersion, createCharge: charge }) }); await data.reload(); await queryClient.invalidateQueries({ queryKey: ['rental-preview', group.id] }); await queryClient.invalidateQueries({ queryKey: ['court-schedule'] }) }, 'Encontros confirmados. Confira o calendário e o financeiro abaixo.') }
  return <><div className="record-overview"><div><Status>{group.status}</Status><p>{weekDays[group.weekDay]} · {group.startTime}–{group.endTime}</p></div>{finance&&<strong>{currency(group.monthlyAmount)} <small>/ mês</small></strong>}<Field label="Competência" type="month" disabled={action.busy} value={month} onChange={v => { setMonth(v); setCharge(false); setSelectedMeeting('') }} /></div><SectionTabs items={tabs} value={section} onChange={setSection}/><Feedback action={action}/>{section==='resumo'&&<><DetailList items={[["Situação", group.status], ['Responsável', group.members.find(m => m.id === group.organizerId)?.name || 'A confirmar'], ['Suplente', group.members.find(m => m.id === group.backupId)?.name], ['Acordo', `${displayDate(group.startDate)}${group.endDate ? ` até ${displayDate(group.endDate)}` : ' · sem término definido'}`], ['Quinto encontro', fifthPolicies.find(p => p.value === group.fifthPolicy)?.label], ...(finance ? [["Mensalidade combinada", currency(group.monthlyAmount)] as [string, string]] : [])]} />
    <div className="record-overview"><p>{meetings.length} encontros em {month.split('-').reverse().join('/')} · {group.members.filter(m=>m.status==='Ativo').length} integrantes cadastrados</p><button className="secondary-link" onClick={()=>setSection('encontros')}>Ver encontros</button><button className="secondary-link" onClick={()=>setSection('integrantes')}>Ver integrantes</button></div>{group.notes&&<Disclosure title="Combinados e origem"><p>{group.notes}</p></Disclosure>}</>}
    {section==='integrantes'&&<section className="rental-section"><h2>Todos da turma</h2>{!group.members.length && <p>Integrantes e responsável a confirmar. O cadastro da turma e dos horários já pode ser utilizado.</p>}<div className="rental-roster">{group.members.map(m => <div key={m.id}><strong>{m.name}</strong><small>{m.id === group.organizerId ? 'Responsável' : m.id === group.backupId ? 'Suplente' : 'Integrante'} · {m.status}</small>{m.phone && <span>{m.phone}</span>}</div>)}</div></section>}
    {section==='encontros'&&<><section className="rental-section"><h2>Encontros do mês</h2>
    {!monthRow && <div className="rental-month-preview"><h3>Revisar antes de reservar</h3>{data.persistenceStatus !== 'connected' ? <p>Conecte-se à arena para revisar e gerar os encontros.</p> : preview.isPending && <p>Consultando o calendário…</p>}{preview.error && <p role="alert">{preview.error.message}</p>}{preview.data && <><p>{preview.data.dates.length} encontros: {preview.data.dates.map(displayDate).join(' · ')}</p>{finance && <p>Valor do mês: <strong>{currency(preview.data.amount)}</strong> · vencimento {preview.data.dueDate ? displayDate(preview.data.dueDate) : 'a confirmar'}</p>}{preview.data.warnings.map(w => <p key={w}>{w}</p>)}{preview.data.errors.length > 0 && <div role="alert"><strong>Resolva antes de gerar:</strong><ul>{preview.data.errors.map(e => <li key={e}>{e}</li>)}</ul></div>}{data.canWrite('rentalGroups') && <><label className="rental-checkbox"><input type="checkbox" checked={charge} onChange={e => setCharge(e.target.checked)} disabled={action.busy || !data.canWrite('financeEntries') || !(preview.data.amount && preview.data.amount > 0) || !preview.data.dueDate} /> Gerar também uma cobrança pendente do aluguel mensal</label><button className="primary-button" disabled={action.busy || data.saving || preview.data.errors.length > 0 || !preview.data.dates.length} onClick={() => void generate()}>{action.busy ? 'Confirmando…' : `Confirmar ${preview.data.dates.length} encontros${charge ? ' e cobrança' : ''}`}</button></>}</>}</div>}
    {monthRow && <><p>Competência gerada. Cada encontro pode ser remarcado ou cancelado pela agenda. Essas alterações não modificam a mensalidade automaticamente.</p><div className="rental-meetings">{meetings.map(r => <ContextLink state={{returnLabel:group.name}} key={r.id} to={`/agenda/${r.id}`}><strong>{displayDate(r.date)}</strong><span>{r.startTime}–{r.endTime}</span><Status>{r.status}</Status></ContextLink>)}</div></>}
    </section>
    {monthRow && meeting && <section className="rental-section"><h2>Presença no encontro</h2><Field label="Encontro" value={meeting.id} onChange={setSelectedMeeting} options={meetings.map(r => ({ value: r.id, label: `${displayDate(r.date)} · ${r.status}` }))} /><p>Marque quem veio. “Não informado” mantém a presença em aberto.</p><div className="rental-roster">{members.map(m => { const presence = data.rentalAttendances.find(p => p.reservationId === meeting.id && p.memberId === m.id); return <Field key={m.id} label={m.name} value={presence?.status ?? 'Não informado'} onChange={status => void action.run(async () => { await data.saveRentalAttendance({ ...presence, name: `${m.name} · ${meeting.date}`, rentalGroupId: group.id, reservationId: meeting.id, memberId: m.id, status: status as 'Presente' | 'Ausente' | 'Não informado' }, presence?.id) }, 'Presença atualizada.')} options={['Não informado', 'Presente', 'Ausente']} disabled={!data.canWrite('rentalAttendances') || data.saving || action.busy || meeting.date > today() || meeting.status === 'Cancelada'} /> })}</div></section>}
    </>}
    {section==='financeiro'&&finance&&<section className="rental-section"><h2>Mensalidade de {month.split('-').reverse().join('/')}</h2>{monthRow?<>{liveEntry?<><DetailList items={[["Valor",currency(liveEntry.amount)],["Situação",liveEntry.status],["Vencimento",displayDate(liveEntry.dueDate)]]}/><ContextLink state={{returnLabel:group.name}} className="primary-link" to={`/financeiro/${liveEntry.id}`}>Ver mensalidade →</ContextLink></>:<Empty action={data.canWrite('financeEntries')&&<ContextLink state={{returnLabel:group.name}} className="primary-link" to={`/financeiro/novo?origin=Locações&sourceKind=rentalMonths&source=${monthRow.id}&month=${month}`}>Registrar mensalidade</ContextLink>}>Sem cobrança ativa nesta competência.</Empty>}</>:<Empty action={<button className="secondary-link" onClick={()=>setSection('encontros')}>Revisar encontros</button>}>Gere os encontros da competência antes de registrar a mensalidade.</Empty>}<p className="arena-hint">O valor combinado não comprova recebimento. A cobrança do aluguel e o consumo no bar têm registros próprios.</p>{owner&&<Link to={`/financeiro/historico?series=mensalistas&month=${month}`}>Consultar controle importado →</Link>}</section>}
    {section==='bar'&&canBar && <section className="rental-section"><h2>A resenha no bar</h2><p>Valores das comandas vinculadas aos encontros desta competência. Recebido considera pagamentos aprovados menos estornos; consumo considera os ajustes da comanda.</p>{bar.error ? <p role="alert">Não foi possível atualizar o bar: {bar.error.message}</p> : <RentalStats items={[["Consumo do grupo", amounts ? currency(amounts.total) : '…'], ['Recebido no bar', amounts ? currency(amounts.paid) : '…'], ['A receber no bar', amounts ? currency(amounts.due) : '…']]} />}<RentalBarPanel group={group} meetings={meetings} links={bar.data ?? []} onLinked={async () => { await bar.refetch() }} /></section>}
  </>
}
