import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter, Routes, Route } from 'react-router-dom'
import { AuthContext, type AuthContextValue } from '../auth/authContext'
import type { AuthUser } from '../auth/types'
import { TeacherLayout,TeacherHome,TeacherRoster } from './TeachingPages'
import { hasPermission,workHome } from '../auth/access'
const teacher:AuthUser={id:'teacher',name:'Professor',email:'teacher@example.invalid',roles:['Teacher'],permissions:['students:read','students:write','projects:read']}
const cls={id:'c1',name:'Iniciantes',weekDay:6,startTime:'08:00',endTime:'09:00',startDate:'2026-10-01',status:'Ativa',capacity:6,enrolled:1}
const clients:QueryClient[]=[]
function mount(path='/professor',user=teacher){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});clients.push(client);const auth={user,isBootstrapping:false,signOut:async()=>{}} as AuthContextValue;return render(<QueryClientProvider client={client}><AuthContext.Provider value={auth}><MemoryRouter initialEntries={[path]}><Routes><Route path="professor" element={<TeacherLayout/>}><Route index element={<TeacherHome/>}/><Route path="turmas/:classId" element={<TeacherRoster/>}/></Route></Routes></MemoryRouter></AuthContext.Provider></QueryClientProvider>)}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}})
afterEach(()=>{cleanup();clients.splice(0).forEach(c=>c.clear());vi.restoreAllMocks()})
it('professor recebe navegação própria e alternância pessoal sem módulos da gestão',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(json({linked:true,classes:[cls]}));mount();await screen.findByRole('heading',{name:'Suas aulas de hoje'});expect(screen.getByRole('navigation',{name:'Área do professor'}).querySelectorAll('a')).toHaveLength(3);expect(screen.getByRole('link',{name:'Minha área'})).toHaveAttribute('href','/minha-area');expect(screen.queryByRole('link',{name:'Gestão'})).not.toBeInTheDocument()})
it('vínculo ausente não vira lista vazia de alunos',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(json({linked:false,classes:[]}));mount();expect(await screen.findByRole('heading',{name:'Seu acesso às turmas está em preparação'})).toBeInTheDocument();expect(screen.queryByText('Nenhuma aula na grade de hoje')).not.toBeInTheDocument()})
it('cliente não consulta a API de professores por URL direta',async()=>{const fetch=vi.spyOn(globalThis,'fetch');mount('/professor',{...teacher,roles:['Student']});expect(await screen.findByRole('heading',{name:'Acesso restrito'})).toBeInTheDocument();expect(fetch).not.toHaveBeenCalled()})
it('registra presença no endpoint delimitado, com versão, e mostra confirmação',async()=>{let status:string|null=null;let version=0;const fetch=vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{if(init?.method==='PUT'){const body=JSON.parse(String(init.body));status=body.status;version++;}return String(input).includes('/classes/')?json({class:cls,date:'2026-10-03',students:[{id:'s1',name:'Ana',presence:status,version}]}):json({linked:true,classes:[cls]})});mount('/professor/turmas/c1?date=2026-10-03');fireEvent.click(await screen.findByRole('button',{name:'Ana: Presente'}));await screen.findByText('Presença de Ana registrada.');expect(fetch).toHaveBeenCalledWith(expect.stringContaining('/classes/c1/presences?date=2026-10-03'),expect.objectContaining({method:'PUT',body:JSON.stringify({studentId:'s1',status:'Presente',version:0})}));expect(screen.getByRole('button',{name:'Ana: Presente'})).toHaveAttribute('aria-pressed','true')})
it('erro de consulta não permite registrar nem indica ausência de alunos',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(async(input)=>String(input).includes('/classes/')?json({message:'Acesso restrito'},403):json({linked:true,classes:[cls]}));mount('/professor/turmas/c1?date=2026-10-03');await screen.findByRole('alert');expect(screen.queryByText('Nenhuma matrícula válida para esta data.')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/Presente/})).not.toBeInTheDocument()})
it('perfis combinados mantêm entrada e limites explícitos',()=>{expect(workHome(teacher)).toBe('/professor');expect(hasPermission(teacher,'students:read')).toBe(false);const bar={...teacher,roles:['Teacher','BarOperator','Student'] as AuthUser['roles'],permissions:[...teacher.permissions,'bar:sales:operate','bar:supervise','bar:stock:read']};expect(hasPermission(bar,'bar:sales:operate')).toBe(true);expect(hasPermission(bar,'bar:supervise')).toBe(false);expect(hasPermission(bar,'bar:stock:read')).toBe(false);expect(workHome({...teacher,roles:['Manager'],permissions:[]})).toBe('/');expect(hasPermission({...teacher,roles:['Manager'],permissions:[]},'users:manage')).toBe(true)})

it('aula experimental confirmada aparece no dia do professor mesmo sem turma regular',async()=>{
 const date=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
 vi.spyOn(globalThis,'fetch').mockResolvedValue(json({linked:true,classes:[],appointments:[{id:'trial1',name:'Aula experimental · Visitante',customerName:'Visitante',date,startTime:'14:00',endTime:'15:00',status:'Confirmada'}]}));mount();expect(await screen.findByRole('heading',{name:'Atividades agendadas'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Aula experimental · Visitante'})).toBeInTheDocument();expect(screen.getByText(/14:00–15:00/)).toBeInTheDocument()
})
