import { useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ApiError } from '../../lib/http'
import { useAuth } from '../auth/authContext'
import { CartReview, Empty, Feedback, Header, Icon, ItemStatus, Payments, Products, Status, Summary, WorkflowSteps, cartTotal } from './components'
import { dateTime, money, parseAmount, postBar, useBarCommand, useBarData, useIntent, type CatalogItem, type Named, type PageResult, type Tab } from './api'
import '../prototype/prototype.css'
import './attendance.css'
import { AccessQr } from './AccessQr'

import { BarFrame, LoadState, useCart, useConfirmationGate, useServiceLocation } from './Core'
export { BarFrame, LoadState, useCart } from './Core'

export function SellPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const [params] = useSearchParams(); const tabId = params.get('comanda')
  const locations = useBarData<Named[]>('/tabs/locations')
  const target = useBarData<Tab>(`/tabs/${tabId}`, Boolean(tabId))
  const [pendingOrder, setPendingOrder] = useConfirmationGate(`order:${user?.id}:${tabId ?? 'sale'}`)
  const [selected, setSelected] = useServiceLocation(user?.id); const [review, setReview] = useState(Boolean(pendingOrder))
  const locationId = tabId ? target.data?.locationId ?? '' : locations.data?.some(location => location.id === selected) ? selected : locations.data?.length === 1 ? locations.data[0].id : ''
  const catalog = useBarData<CatalogItem[]>(`/tabs/catalog?locationId=${encodeURIComponent(locationId)}`, Boolean(locationId))
  const [cart, setCart] = useCart(tabId ?? 'sale', user?.id); const command = useBarCommand(); const intent = useIntent(`cart:${tabId ?? 'sale'}`)
  const products = catalog.data ?? []; const ready = cart.every(row => products.some(product => product.id === row.productId && !product.prepared))
  const fingerprint = `${locationId}:${cart.map(row => `${row.productId}:${row.quantity}`).sort().join('|')}`
  async function submit(deliver: boolean) {
    if (!locationId || !catalog.data || catalog.isError) { command.setError('Escolha o local de atendimento e confira os produtos antes de continuar.'); return }
    if (pendingOrder && pendingOrder !== (deliver ? 'deliver' : 'queue')) return
    setPendingOrder(deliver ? 'deliver' : 'queue')
    const result = await command.run(async () => {
      const tab = tabId ? target.data : await postBar<Tab>('/tabs', { operationId: intent(`open:${fingerprint}`), locationId, mode: 'Immediate' })
      if (!tab) throw new Error('Atualize a comanda antes de continuar.')
      return postBar<Tab>(`/tabs/${tab.id}/items`, { operationId: intent(`add:${fingerprint}:${deliver}`), items: cart, deliver })
    })
    if (result.ok) { setPendingOrder(''); intent(`open:${fingerprint}`, true); intent(`add:${fingerprint}:${deliver}`, true); setCart([]); setReview(false); navigate(deliver && !tabId ? `/atendimento/receber/${result.value.id}` : `/atendimento/comandas/${result.value.id}`) }
    else if (result.error instanceof ApiError && [400, 422].includes(result.error.status)) setPendingOrder('')
  }
  return <BarFrame><Header title={target.data ? `Vender · Comanda ${target.data.number}` : 'Vender'} description="Toque no produto. Depois confira o pedido." /><WorkflowSteps current={review ? 'review' : 'products'} />
    {!tabId && locations.data && locations.data.length > 1 && <label className="ux-field">Local de atendimento<select value={locationId} disabled={Boolean(locationId && cart.length > 0) || command.busy || Boolean(pendingOrder)} onChange={event => setSelected(event.target.value)}><option value="" disabled>Escolha o local</option>{locations.data.map(value => <option key={value.id} value={value.id}>{value.name}</option>)}</select></label>}
    <LoadState query={locations} /><LoadState query={catalog} />{tabId && <LoadState query={target} />}<Feedback {...command} />{pendingOrder && <p className="ux-notice warning" role="status">Este pedido precisa ser confirmado. Repita o mesmo registro antes de alterar os produtos.</p>}
    {!locationId && !tabId && !locations.isLoading && !locations.isError && <Empty title={locations.data?.length ? 'Escolha o local de atendimento' : 'Atendimento ainda não configurado'}><p>{locations.data?.length ? 'Selecione acima onde esta venda será atendida. Depois, os produtos e o estoque aparecerão aqui.' : 'Peça à gestão para cadastrar um local de estoque do bar.'}</p></Empty>}
    {Boolean(locationId) && (review ? <><CartReview products={products} cart={cart} /><div className="ux-actions lb-review-actions"><button className="ux-button secondary" disabled={command.busy || Boolean(pendingOrder)} onClick={() => setReview(false)}>Alterar pedido</button><button className={`ux-button ${ready ? 'secondary' : 'primary'}`} disabled={command.busy || pendingOrder === 'deliver' || !cart.length || catalog.isError || Boolean(tabId && !target.data)} onClick={() => void submit(false)}><Icon name="orders" />{tabId ? 'Adicionar à comanda' : 'Registrar pedido'}</button>{ready && <button className="ux-button primary" disabled={command.busy || pendingOrder === 'queue' || !cart.length || catalog.isError} onClick={() => void submit(true)}><Icon name="check" />Registrar e entregar</button>}</div><p className="ux-note">Itens preparados seguem para a fila de pedidos. O consumo só entra no total após ser aceito.</p></> : <><Products products={products} cart={cart} onChange={next => { if (!tabId) setSelected(locationId); setCart(next) }} disabled={command.busy || Boolean(pendingOrder) || Boolean(tabId && !target.data)} />{cart.length > 0 && <div className="ux-sticky-action"><span><strong>{money(cartTotal(products, cart))}</strong><small>{cart.reduce((total, row) => total + row.quantity, 0)} itens no pedido</small></span><button className="ux-button primary" onClick={() => setReview(true)}>Conferir pedido<Icon name="arrow" /></button></div>}</>)}
  </BarFrame>
}

export function TabsPage() {
  const { user } = useAuth(); const canOperate = user?.permissions.includes('bar:sales:operate')
  const [params, setParams] = useSearchParams(); const search = params.get('busca') ?? ''; const page = Math.max(1, Number(params.get('pagina')) || 1)
  const query = useBarData<PageResult<Tab>>(`/tabs?state=Open&search=${encodeURIComponent(search)}&page=${page}&pageSize=24`)
  const locations = useBarData<Named[]>('/tabs/locations', Boolean(canOperate)); const [selectedLocation, setLocation] = useServiceLocation(user?.id); const [name, setName] = useState(''); const [opening, setOpening] = useState(false)
  const location = locations.data?.some(row => row.id === selectedLocation) ? selectedLocation : locations.data?.length === 1 ? locations.data[0].id : ''
  const command = useBarCommand(); const intent = useIntent('new-tab'); const navigate = useNavigate()
  async function open() { if (!canOperate || !location) return; const result = await command.run(() => postBar<Tab>('/tabs', { operationId: intent('open'), locationId: location, name, mode: 'Tab' })); if (result.ok) { setLocation(location); intent('open', true); navigate(`/atendimento/comandas/${result.value.id}`) } }
  return <BarFrame><Header title="Comandas" description="Procure pelo número ou nome.">{canOperate && <button className="ux-button primary" onClick={() => setOpening(!opening)}><Icon name="plus" />Abrir comanda</button>}</Header><Feedback {...command} />
    {canOperate && opening && <form className="ux-panel" onSubmit={event => { event.preventDefault(); void open() }}><h2>Nova comanda</h2><label className="ux-field">Nome (opcional)<input value={name} maxLength={120} disabled={command.busy} onChange={event => { setName(event.target.value); intent('open', true) }} placeholder="Visitante" /></label>{(locations.data?.length ?? 0) > 1 && <label className="ux-field">Local<select value={location} disabled={command.busy} onChange={event => { setLocation(event.target.value); intent('open', true) }}><option value="" disabled>Escolha o local</option>{locations.data?.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>}<LoadState query={locations} /><button className="ux-button primary" disabled={command.busy || !location}>Abrir sem cadastro</button></form>}
    <label className="ux-search"><Icon name="search" /><input value={search} type="search" placeholder="Número ou nome" aria-label="Buscar comanda" onChange={event => setParams({ busca: event.target.value, pagina: '1' })} /></label><LoadState query={query} />
    <div className="ux-grid ux-account-grid">{query.data?.items.map(tab => <Link className="ux-account-card" key={tab.id} to={`/atendimento/comandas/${tab.id}?retorno=${encodeURIComponent(`/atendimento/comandas${params.size?`?${params}`:''}`)}`}><span className="ux-account-number">{tab.number}</span><strong>{tab.name || 'Visitante'}</strong><span className="ux-total">Falta pagar<strong>{money(tab.due)}</strong></span>{tab.pending > 0 && <Status tone="warning">Pix pendente: {money(tab.pending)}</Status>}<span className="ux-card-link">Abrir comanda<Icon name="arrow" /></span></Link>)}</div>{query.data?.total === 0 && <Empty title="Nenhuma comanda encontrada" />}
    {query.data && <div className="ux-pagination"><button className="ux-button secondary" disabled={page === 1} onClick={() => setParams({ busca: search, pagina: String(page - 1) })}>Anterior</button><span>{query.data.total} comandas · Página {page}</span><button className="ux-button secondary" disabled={page * 24 >= query.data.total} onClick={() => setParams({ busca: search, pagina: String(page + 1) })}>Próxima</button></div>}
  </BarFrame>
}

export function TabDetailsPage() {
  const { tabId = '' } = useParams(); const query = useBarData<Tab>(`/tabs/${tabId}`); const tab = query.data
  const [params] = useSearchParams(); const returnTo = params.get('retorno') ?? ''
  const back = returnTo.startsWith('/bar/indicadores') || returnTo.startsWith('/atendimento/comandas?') ? returnTo : '/atendimento/comandas'
  const command = useBarCommand(); const intent = useIntent(tabId); const { user } = useAuth()
  const [adjusting, setAdjusting] = useState(false); const [adjustmentKind, setAdjustmentKind] = useState('Discount'); const [adjustmentValue, setAdjustmentValue] = useState(''); const [adjustmentReason, setAdjustmentReason] = useState('')
  const [qr, setQr] = useState<{ token: string; expiresAtUtc: string } | null>(null); const [reason, setReason] = useState(''); const [selected, setSelected] = useState<string | null>(null)
  async function action(itemId: string, actionName: string) {
    const result = await command.run(() => postBar<Tab>(`/tabs/${tabId}/items/${itemId}/${actionName}`, { operationId: intent(`${itemId}:${actionName}`), reason }))
    if (result.ok) { setSelected(null); setReason(''); command.setMessage('Operação confirmada.') }
  }
  async function access() { const result = await command.run(() => postBar<{ token: string; expiresAtUtc: string }>(`/tabs/${tabId}/access`, { operationId: intent('access', true) })); if (result.ok) setQr(result.value) }
  async function revokeAccess() { const result = await command.run(() => postBar(`/tabs/${tabId}/access/revoke`, { operationId: intent('revoke') })); if (result.ok) { intent('revoke', true); setQr(null); command.setMessage('Acesso encerrado.') } }
  const supervisor = user?.permissions.includes('bar:supervise'); const canOperate = user?.permissions.includes('bar:sales:operate')
  return <BarFrame><Header title={tab ? `Comanda ${tab.number}` : 'Comanda'} description={tab?.name || 'Visitante'} back={back} /><LoadState query={query} /><Feedback {...command} />{tab && <><section className="ux-panel ux-account-header"><Summary tab={tab} /><div className="ux-actions">{tab.state === 'Open' && canOperate && <><Link className="ux-button primary" to={`/atendimento/vender?comanda=${tabId}`}><Icon name="plus" />Adicionar produtos</Link><Link className="ux-button secondary" to={`/atendimento/receber/${tabId}`}>Receber</Link><button className="ux-button secondary" disabled={command.busy} onClick={() => void access()}>Acesso do cliente</button><button className="ux-button secondary" disabled={command.busy} onClick={() => void revokeAccess()}>Encerrar acesso do cliente</button></>}</div></section>
      {qr && <section className="ux-panel"><h2>Acesso do cliente</h2><AccessQr url={`${window.location.origin}/cliente#token=${encodeURIComponent(qr.token)}`} /><p>Válido até {dateTime(qr.expiresAtUtc)}. Compartilhe somente com esta pessoa.</p><Link className="ux-button primary" to={`/cliente#token=${encodeURIComponent(qr.token)}`} target="_blank" rel="noreferrer">Abrir catálogo do cliente</Link><button className="ux-button secondary" disabled={command.busy} onClick={() => void revokeAccess()}>Encerrar acesso</button><p className="ux-note lb-access-link">{`${window.location.origin}/cliente#token=${encodeURIComponent(qr.token)}`}</p></section>}
      <section className="ux-panel"><h2>Consumo e pedidos</h2>{!tab.items.length && <p>Adicione os primeiros produtos.</p>}{tab.items.map(item => <article className="ux-list-row ux-consumption-row" key={item.id}><div><strong>{item.quantity} × {item.name}</strong><ItemStatus item={item} /><small>{dateTime(item.createdAtUtc)}{item.reason && ` · ${item.reason}`}</small>{item.recipeId && user?.permissions.includes('bar:catalog:write') && <Link to={`/bar/receitas/${item.productId}?version=${item.recipeId}`}>Ver receita usada · versão {item.recipeVersion}</Link>}</div><div><strong>{money(item.total)}</strong><div className="ux-actions">{canOperate && item.allowedActions?.includes('accept') && <button className="ux-button secondary" disabled={command.busy} onClick={() => void action(item.id, 'accept')}>Aceitar</button>}{canOperate && item.allowedActions?.includes('fulfill') && <button className="ux-button primary" disabled={command.busy} onClick={() => void action(item.id, 'fulfill')}>Entregar</button>}{supervisor && item.allowedActions?.includes('reverse') && <button className="ux-button danger" onClick={() => setSelected(item.id)}>Corrigir consumo</button>}</div></div></article>)}</section>
      {selected && <form className="ux-panel" onSubmit={event => { event.preventDefault(); void action(selected, 'reverse') }}><h2>Corrigir consumo</h2><label className="ux-field">Motivo obrigatório<input required value={reason} minLength={3} maxLength={500} onChange={event => setReason(event.target.value)} /></label><p className="ux-note">O estoque só deve retornar após conferência física. Esta correção não retorna estoque automaticamente.</p><div className="ux-actions"><button className="ux-button danger" disabled={command.busy}>Confirmar correção</button><button className="ux-button secondary" type="button" onClick={() => setSelected(null)}>Voltar</button></div></form>}
      {supervisor && tab.state === 'Open' && tab.payable > 0 && <button className="ux-button secondary" onClick={() => setAdjusting(!adjusting)}>Autorizar desconto ou cortesia</button>}{adjusting && <form className="ux-panel" onSubmit={async event => { event.preventDefault(); const amount = adjustmentKind === 'Courtesy' ? tab.payable : parseAmount(adjustmentValue); if (!Number.isFinite(amount) || amount <= 0 || amount > tab.payable) { command.setError('Confira o valor autorizado.'); return } const result = await command.run(() => postBar<Tab>(`/tabs/${tabId}/adjustments`, { operationId: intent('adjustment'), kind: adjustmentKind, amount, reason: adjustmentReason })); if (result.ok) { intent('adjustment', true); setAdjusting(false); setAdjustmentReason(''); setAdjustmentValue(''); command.setMessage('Autorização registrada.') } }}><h2>Autorização do supervisor</h2><label className="ux-field">Tipo<select value={adjustmentKind} disabled={command.busy} onChange={event => { setAdjustmentKind(event.target.value); intent('adjustment', true) }}><option value="Discount">Desconto por valor</option><option value="Courtesy">Cortesia de todo o saldo disponível</option></select></label>{adjustmentKind === 'Discount' && <label className="ux-field">Valor do desconto (R$)<input required inputMode="decimal" value={adjustmentValue} disabled={command.busy} onChange={event => { setAdjustmentValue(event.target.value); intent('adjustment', true) }} /></label>}<label className="ux-field">Motivo obrigatório<input required minLength={3} maxLength={500} value={adjustmentReason} disabled={command.busy} onChange={event => { setAdjustmentReason(event.target.value); intent('adjustment', true) }} /></label><div className="ux-actions"><button className="ux-button primary" disabled={command.busy}>Confirmar autorização</button><button type="button" className="ux-button secondary" disabled={command.busy} onClick={() => setAdjusting(false)}>Voltar</button></div></form>}<Payments tab={tab} />{canOperate && tab.state === 'Open' && tab.due === 0 && tab.pending === 0 && !tab.items.some(item => ['Requested', 'Accepted'].includes(item.state)) && <button className="ux-button secondary" disabled={command.busy} onClick={async () => { const result = await command.run(() => postBar<Tab>(`/tabs/${tabId}/close`, { operationId: intent('close') })); if (result.ok) command.setMessage('Comanda encerrada.') }}>Encerrar comanda</button>}
      <details className="ux-panel"><summary>Histórico da comanda</summary><ol className="ux-timeline">{tab.history?.map(row => <li key={row.id}>{historyLabel(row.kind)}{row.amount !== 0 && ` · ${money(row.amount)}`}<small>{dateTime(row.createdAtUtc)}{row.reason && ` · ${row.reason}`}</small></li>)}</ol></details>
    </>}</BarFrame>
}
const historyLabel = (kind: string) => ({ Open: 'Comanda aberta', Opened: 'Comanda aberta', ItemAdded: 'Produto adicionado', Requested: 'Pedido recebido, aguardando aceite', Accepted: 'Pedido aceito', Fulfilled: 'Produto entregue', Rejected: 'Pedido recusado', Reversed: 'Consumo corrigido', Payment: 'Pagamento registrado', PaymentApproved: 'Pagamento confirmado', PaymentPending: 'Pix aguardando confirmação', PaymentDeclined: 'Pagamento não confirmado', PaymentRefunded: 'Estorno confirmado', Discount: 'Desconto autorizado', Courtesy: 'Cortesia autorizada', Refund: 'Estorno', Closed: 'Comanda encerrada', Access: 'Acesso de cliente emitido', AccessRevoked: 'Acesso do cliente encerrado', FeeReconciled: 'Taxa conciliada' }[kind] ?? 'Alteração na comanda')

export function OrdersPage() {
  const [params, setParams] = useSearchParams(); const page = Math.max(1, Number(params.get('pagina')) || 1)
  const query = useBarData<PageResult<Tab>>(`/tabs?state=Orders&page=${page}&pageSize=24`); const command = useBarCommand(); const intent = useIntent('orders')
  const [refusing, setRefusing] = useState<{ tabId: string; itemId: string } | null>(null); const [reason, setReason] = useState('')
  async function action(tabId: string, itemId: string, name: string) { const result = await command.run(() => postBar<Tab>(`/tabs/${tabId}/items/${itemId}/${name}`, { operationId: intent(`${itemId}:${name}`), reason })); if (result.ok) { setRefusing(null); setReason(''); command.setMessage(name === 'fulfill' ? 'Entrega confirmada.' : name === 'accept' ? 'Pedido aceito.' : 'Pedido recusado.') } }
  return <BarFrame><Header title="Pedidos" description="Aceite o pedido. Depois confirme a entrega." /><Feedback {...command} /><LoadState query={query} />{refusing && <form className="ux-panel" onSubmit={event => { event.preventDefault(); void action(refusing.tabId, refusing.itemId, 'reject') }}><label className="ux-field">Por que o pedido foi recusado?<input value={reason} required minLength={3} maxLength={500} onChange={event => setReason(event.target.value)} /></label><div className="ux-actions"><button className="ux-button danger" disabled={command.busy}>Confirmar recusa</button><button className="ux-button secondary" type="button" onClick={() => setRefusing(null)}>Voltar</button></div></form>}
    <div className="ux-grid ux-order-grid">{query.data?.items.flatMap(tab => tab.items.filter(item => ['Requested', 'Accepted'].includes(item.state)).map(item => <article className="ux-panel lb-order-card" key={item.id}><Link className="lb-order-comanda" to={`/atendimento/comandas/${tab.id}`}><span>Comanda <strong>{tab.number}</strong></span><h2>{tab.name || 'Visitante'}<Icon name="arrow" /></h2></Link><strong className="lb-order-product">{item.quantity} × {item.name}</strong><p className="ux-note">{dateTime(item.createdAtUtc)}</p><ItemStatus item={item} /><div className="ux-actions">{item.state === 'Requested' ? <><button className="ux-button primary" disabled={command.busy} onClick={() => void action(tab.id, item.id, 'accept')}>Aceitar</button><button className="ux-button danger" disabled={command.busy} onClick={() => setRefusing({ tabId: tab.id, itemId: item.id })}>Recusar</button></> : <button className="ux-button primary" disabled={command.busy} onClick={() => void action(tab.id, item.id, 'fulfill')}>Entregar</button>}</div></article>))}</div>{query.data?.total === 0 && <Empty title="Nenhum pedido aguardando" />}<div className="ux-pagination"><button className="ux-button secondary" disabled={page === 1} onClick={() => setParams({ pagina: String(page - 1) })}>Anterior</button><span>Página {page}</span><button className="ux-button secondary" disabled={!query.data || page * 24 >= query.data.total} onClick={() => setParams({ pagina: String(page + 1) })}>Próxima</button></div>
  </BarFrame>
}
