import { useState, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { Icon, Status } from '../prototype/components'
import { dateTime, itemLabels, money, paymentLabels, type CatalogItem, type CartLine, type Tab, type TabItem, type TabPayment } from './api'
export { Icon, Status }

export function Header({ title, description, back, children }: { title: string; description?: string; back?: string; children?: ReactNode }) {
  return <header className="ux-page-header">{back && <Link className="ux-back" to={back}><Icon name="back" />Voltar</Link>}<div className="ux-heading-line"><div><h1>{title}</h1>{description && <p className="ux-description">{description}</p>}</div>{children}</div></header>
}
export function Feedback({ error, message, busy }: { error?: string; message?: string; busy?: boolean }) {
  return <>{error && <p className="ux-notice error" role="alert"><Icon name="alert" />{error}</p>}{message && <p className="ux-notice success" role="status"><Icon name="check" />{message}</p>}{busy && <p className="ux-note" role="status">Aguardando confirmação…</p>}</>
}
export function Empty({ title, children }: { title: string; children?: ReactNode }) { return <section className="ux-empty"><span className="ux-empty-symbol"><Icon name="sell" size={32} /></span><h2>{title}</h2>{children}</section> }
export function WorkflowSteps({ current }: { current: 'products' | 'review' | 'payment' }) {
  const steps = [{ key: 'products', label: 'Escolher' }, { key: 'review', label: 'Conferir' }, { key: 'payment', label: 'Receber' }]
  const active = steps.findIndex(step => step.key === current)
  return <ol className="lb-order-steps" aria-label="Etapas da venda">{steps.map((step, index) => <li key={step.key} className={index === active ? 'current' : index < active ? 'complete' : ''} aria-current={index === active ? 'step' : undefined}><span aria-hidden="true">{index < active ? <Icon name="check" size={18} /> : index + 1}</span>{step.label}</li>)}</ol>
}
export function BalanceState({ tab, client = false }: { tab: Tab; client?: boolean }) {
  const requested = tab.items.some(item => item.state === 'Requested')
  const empty = tab.total === 0 && tab.paid === 0
  const title = tab.pending > 0 ? 'Aguarde a confirmação do pagamento' : requested ? 'Esperando a equipe confirmar' : empty ? 'Nenhum valor para pagar' : 'Tudo pago'
  const description = tab.pending > 0 ? 'O pagamento ainda está sendo conferido. Aguarde antes de pagar novamente.' : requested ? 'Seu pedido só entra no total depois de ser aceito pela equipe.' : empty ? client ? 'Os itens aceitos pela equipe aparecerão no total da sua comanda.' : 'Adicione produtos ou aguarde a confirmação dos pedidos.' : client ? 'Obrigado! Você pode acompanhar os pedidos na sua comanda.' : 'O saldo desta comanda foi recebido.'
  return <div className={`lb-balance-state ${tab.pending > 0 || requested ? 'waiting' : 'settled'}`} role="status"><span className="lb-balance-icon"><Icon name={tab.pending > 0 || requested ? 'clock' : empty ? 'tabs' : 'check'} size={30} /></span><div><h2>{title}</h2><p>{description}</p></div></div>
}
export function Summary({ tab }: { tab: Tab }) {
  return <>{Boolean(tab.discount) && <p className="ux-note">Consumo: {money(tab.gross ?? tab.total + (tab.discount ?? 0))} · Desconto / cortesia autorizado: {money(tab.discount ?? 0)}</p>}<dl className="ux-summary" aria-label="Valores da comanda"><div><dt>Total</dt><dd>{money(tab.total)}</dd></div><div><dt>Já pago</dt><dd>{money(tab.paid)}</dd></div><div><dt>Pagamento pendente</dt><dd>{money(tab.pending)}</dd></div><div className="ux-total"><dt>Falta pagar</dt><dd>{money(tab.due)}</dd></div></dl></>
}
export function ItemStatus({ item }: { item: TabItem }) { return <Status tone={item.state === 'Fulfilled' ? 'success' : item.state === 'Requested' || item.state === 'Accepted' ? 'warning' : item.state === 'Rejected' ? 'danger' : 'neutral'}>{itemLabels[item.state] ?? item.state}</Status> }
export function PaymentStatus({ payment }: { payment: TabPayment }) { return <Status tone={payment.state === 'Approved' ? 'success' : payment.state === 'Pending' ? 'warning' : 'danger'}>{payment.state === 'Approved' ? 'Pagamento confirmado' : payment.state === 'Pending' ? 'Esperando confirmação' : 'Pagamento não confirmado'}</Status> }
export function Payments({ tab, client = false }: { tab: Tab; client?: boolean }) {
  return <section className="ux-panel"><h2>{client ? 'Seus pagamentos' : 'Pagamentos'}</h2>{!tab.payments.length && <p>Nenhum pagamento registrado.</p>}{tab.payments.map(payment => <article className="ux-list-row" key={payment.id}><div><strong>{paymentLabels[payment.method]} · {money(payment.amount)}</strong><small>{dateTime(payment.createdAtUtc)}</small><PaymentStatus payment={payment} />{payment.refunded > 0 && <small>Estornado: {money(payment.refunded)}</small>}</div>{!client && <Link className="ux-button secondary" to={payment.state === 'Approved' ? `/atendimento/comprovante/${tab.id}/${payment.id}` : `/atendimento/receber/${tab.id}?paymentId=${payment.id}`}>{payment.state === 'Approved' ? 'Ver comprovante' : 'Ver pagamento'}</Link>}</article>)}</section>
}
export const cartTotal = (products: CatalogItem[], cart: CartLine[]) => Math.round(cart.reduce((sum, row) => sum + (products.find(product => product.id === row.productId)?.salePrice ?? 0) * row.quantity, 0) * 100) / 100
export function CartReview({ products, cart }: { products: CatalogItem[]; cart: CartLine[] }) {
  return <section className="ux-panel lb-cart-review"><h2>Conferir pedido</h2><p className="ux-note">Confira os produtos e as quantidades antes de continuar.</p>{cart.map(row => { const product = products.find(product => product.id === row.productId); return <div className="ux-list-row" key={row.productId}><strong>{row.quantity} × {product?.shortName || product?.name || 'Produto'}</strong><strong>{money((product?.salePrice ?? 0) * row.quantity)}</strong></div> })}<p className="ux-total"><span>Total do pedido</span><strong>{money(cartTotal(products, cart))}</strong></p></section>
}
export function Products({ products, cart, onChange, disabled }: { products: CatalogItem[]; cart: CartLine[]; onChange: (next: CartLine[]) => void; disabled?: boolean }) {
  const [category, setCategory] = useState('Todos'); const [search, setSearch] = useState('')
  const stocked = products.filter(product => (product.available ?? 0) >= 1 || cart.some(row => row.productId === product.id))
  const hasFavorites = stocked.some(product => product.favorite)
  const selectedCategory = (category === 'Favoritos' && !hasFavorites) || (!['Todos', 'Favoritos'].includes(category) && !stocked.some(product => product.categoryName === category)) ? 'Todos' : category
  const categories = [...(hasFavorites ? ['Favoritos'] : []), 'Todos', ...new Set(stocked.map(product => product.categoryName).filter(Boolean))]
  const visible = [...stocked].sort((a, b) => a.displayOrder - b.displayOrder || a.name.localeCompare(b.name)).filter(product => (!search && selectedCategory === 'Favoritos' ? product.favorite : !search && !['Todos', 'Favoritos'].includes(selectedCategory) ? product.categoryName === selectedCategory : true) && `${product.name} ${product.shortName}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')))
  const update = (productId: string, quantity: number) => onChange(quantity > 0 ? [...cart.filter(row => row.productId !== productId), { productId, quantity }] : cart.filter(row => row.productId !== productId))
  return <section className="lb-product-picker" aria-label="Escolher produtos"><label className="ux-search"><Icon name="search" /><input type="search" aria-label="Procurar produto" placeholder="Procurar produto" value={search} onChange={event => setSearch(event.target.value)} /></label><div className="ux-categories" aria-label="Categorias">{categories.map(value => <button type="button" className={selectedCategory === value ? 'selected' : ''} aria-pressed={selectedCategory === value} key={value} onClick={() => setCategory(value)}>{value}</button>)}</div><div className="ux-products">{visible.map(product => {
    const count = cart.find(row => row.productId === product.id)?.quantity ?? 0; const limit = Math.max(0, Math.floor(product.available ?? 0))
    const name = product.shortName || product.name
    return <article className={`ux-product ${count > 0 ? 'in-cart' : ''} ${limit === 0 ? 'unavailable' : ''}`} key={product.id}><button type="button" className="ux-product-add" aria-label={`Adicionar ${name} por ${money(product.salePrice)}${limit === 0 ? ' · Esgotado' : ''}`} disabled={disabled || count >= limit} onClick={() => update(product.id, count + 1)}><div className="ux-product-art"><span className="lb-product-fallback"><Icon name={product.prepared ? 'orders' : 'sell'} size={48} /></span>{product.imageUrl && <img src={product.imageUrl} alt="" loading="lazy" referrerPolicy="no-referrer" onError={event => { event.currentTarget.hidden = true }} />}{product.prepared && <span className="ux-product-preparation"><Icon name="clock" size={14} />Preparado</span>}{count > 0 && <span className="ux-product-count" aria-hidden="true">{count}</span>}</div><strong>{name}</strong><span className="ux-product-price">{money(product.salePrice)}<span className="ux-product-plus"><Icon name="plus" size={18} /></span></span>{limit === 0 ? <span className="ux-product-unavailable">Sem estoque disponível</span> : <span className="ux-note">Em estoque: {product.available?.toLocaleString('pt-BR')}</span>}</button>{count > 0 && <div className="ux-quantity"><button type="button" aria-label={`Retirar uma unidade de ${name}`} disabled={disabled} onClick={() => update(product.id, count - 1)}><Icon name="minus" /></button><output aria-label={`Quantidade de ${name}`} aria-live="polite">{count}</output><button type="button" aria-label={`Adicionar uma unidade de ${name}`} disabled={disabled || count >= limit} onClick={() => update(product.id, count + 1)}><Icon name="plus" /></button></div>}</article>
  })}</div>{!visible.length && <Empty title={stocked.length ? 'Nenhum produto nesta seleção' : 'Nenhum produto disponível'}><p>{stocked.length ? 'Tente outro nome ou veja todos os produtos.' : 'Os produtos aparecem aqui quando há saldo disponível no estoque.'}</p>{stocked.length > 0 && <button type="button" className="ux-button secondary" onClick={() => { setSearch(''); setCategory('Todos') }}>Mostrar todos os produtos</button>}</Empty>}</section>
}
