import { useRef, useState, type FormEvent } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useAuth } from '../auth/authContext'
import { ApiError, apiFetch } from '../../lib/http'
import { money } from '../attendance/api'
import type { Account } from '../billing/api'
import { HelpContact } from './ClientLayout'
import { dayLabel, label, messageOf, send, today, usePortal, type Appointment, type Options, type PortalRequest, type Profile } from './api'

export function QueryState({query}:{query:{isPending:boolean;isError:boolean;refetch:()=>unknown}}) { return query.isPending?<p role="status">Carregando sua área…</p>:query.isError?<div className="portal-alert" role="alert">Não foi possível atualizar. <button onClick={()=>void query.refetch()}>Tentar novamente</button></div>:null }
export function PortalHome() {
  const profile=usePortal<Profile>('profile');const agenda=usePortal<Appointment[]>('agenda');const requests=usePortal<PortalRequest[]>('requests');const {user}=useAuth()
  const accounts=useQuery({queryKey:['billing',user?.id,'/api/v1/me/billing'],queryFn:()=>apiFetch<Account[]>('/api/v1/me/billing/accounts'),refetchOnWindowFocus:true})
  const next=agenda.data?.find(a=>a.canChange);const pending=requests.data?.filter(r=>['Sent','Reviewing','Alternative'].includes(r.status))??[]
  const due=(!accounts.isError ? accounts.data : undefined)?.reduce((total,a)=>total+a.payable,0);const bar=(!accounts.isError ? accounts.data : undefined)?.some(a=>a.kind==='Bar'&&a.state==='Open')
  return <><header className="portal-title"><p>Sua Long Beach</p><h1>Olá, {(profile.data?.name??user?.name??'').split(' ')[0]}</h1><span>Seu próximo encontro com a areia começa aqui.</span></header><QueryState query={agenda}/>
    {next?<section className="portal-next"><span className="portal-eyebrow">Seu próximo compromisso</span><h2>{next.title}</h2><p className="portal-time">{dayLabel(next.date)}<br/>{next.startTime}–{next.endTime}</p><p>{next.court}{next.teacher&&` · ${next.teacher}`}</p><Link className="portal-primary" to={`/minha-area/agenda?atividade=${encodeURIComponent(next.key)}`}>Ver meu compromisso</Link>{profile.data?.reminders&&next.date===today()&&<p role="status">É hoje! Confira o horário e chegue alguns minutos antes.</p>}</section>:!agenda.isPending&&!agenda.isError&&<section className="portal-next"><h2>Vamos marcar seu próximo jogo?</h2><p>Você ainda não tem atividades confirmadas nos próximos 60 dias.</p><Link className="portal-primary" to="/minha-area/solicitar?tipo=Trial">Experimentar uma aula</Link></section>}
    <div className="portal-quick-actions"><Link to="/minha-area/solicitar?tipo=Reservation">Solicitar quadra <span>Escolha um horário</span></Link><Link to="/minha-area/solicitar?tipo=Trial">Aula experimental <span>Conheça a escola</span></Link></div>
    <section className="portal-card"><h2>Suas solicitações</h2><QueryState query={requests}/>{pending.length>0?<><p>{pending.length} solicitação(ões) em acompanhamento.</p><Link to="/minha-area/agenda#solicitacoes">Ver respostas da equipe</Link></>:!requests.isPending&&!requests.isError&&<p>Nenhuma solicitação aguardando resposta.</p>}{requests.data?.filter(r=>r.status==='Confirmed'||r.status==='Declined').slice(0,2).map(r=><p key={r.id}>{label(r.kind)}: <strong>{label(r.status)}</strong> — {r.reply}</p>)}</section>
    {bar&&<section className="portal-card"><h2>Sua comanda está aberta</h2><Link to="/minha-area/bar">Pedir ou acompanhar no bar</Link></section>}
    <section className="portal-card"><h2>Pagamentos</h2><QueryState query={accounts}/>{accounts.data&&!accounts.isError&&<><p>{due?`${money(due)} disponível para pagar`:'Nenhum valor disponível para pagar agora.'}</p><Link to="/minha-area/pagamentos">Ver minhas contas</Link></>}</section>
  </>
}
function AppointmentCard({appointment:a,expanded=false}:{appointment:Appointment;expanded?:boolean}) {
  const cache=useQueryClient();const [score,setScore]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false)
  async function rate(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{await send('/api/v1/me/portal/ratings',{appointmentKey:a.key,score:Number(score)});setMessage('Obrigado por avaliar sua visita.');await cache.invalidateQueries({queryKey:['portal']})}catch(e){setMessage(messageOf(e))}finally{setBusy(false)}}
  return <article className="portal-card"><div className="portal-card-top"><span>{a.kind}</span><strong className="portal-status">{a.status}</strong></div><h2>{a.title}</h2><p>{dayLabel(a.date)} · {a.startTime}–{a.endTime}</p><p>{a.court}{a.teacher&&` · ${a.teacher}`}</p><details open={expanded||undefined}><summary>Detalhes e opções</summary><p>{a.instructions}</p>{a.canChange&&<div className="portal-actions"><Link to={`/minha-area/solicitar?tipo=Reschedule&atividade=${encodeURIComponent(a.key)}`}>Solicitar remarcação</Link><Link to={`/minha-area/solicitar?tipo=Cancellation&atividade=${encodeURIComponent(a.key)}`}>Solicitar cancelamento</Link></div>}<Link to="/minha-area/ajuda">Preciso de ajuda</Link></details>
    {a.canRate&&<form onSubmit={e=>void rate(e)}><label>Como foi sua visita?<select required value={score} onChange={e=>setScore(e.target.value)}><option value="">Escolha uma nota</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} de 5</option>)}</select></label><button disabled={busy}>{busy?'Enviando…':'Enviar avaliação'}</button></form>}{a.rating&&<p>Você avaliou esta visita com {a.rating} de 5.</p>}{message&&<p role="status">{message}</p>}
  </article>
}
export function RequestCard({request:r}:{request:PortalRequest}) {
  const options=usePortal<Options>('options');const cache=useQueryClient();const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  async function accept(){setBusy(true);setError('');try{await send(`/api/v1/me/portal/requests/${r.id}/accept`,{version:r.version});await cache.invalidateQueries({queryKey:['portal']})}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
  return <article className="portal-card"><div className="portal-card-top"><span>{label(r.kind)}</span><strong className="portal-status">{label(r.status)}</strong></div>{r.date&&<p>{dayLabel(r.date)} · {r.startTime}–{r.endTime}</p>}{r.courtId&&<p>{options.data?.courts.find(c=>c.id===r.courtId)?.name??'Quadra indicada pela equipe'}</p>}{r.amount!=null&&<p>Valor combinado: {money(r.amount)}</p>}{r.message&&<p>Você: {r.message}</p>}{r.reply&&<p><strong>Resposta da equipe:</strong> {r.reply}</p>}{r.history && r.history.length > 1 && <details><summary>Histórico da solicitação</summary><ol>{r.history.map((h,i)=><li key={i}><strong>{label(h.status)}</strong> · {new Date(h.atUtc).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}<p>{h.reply}</p>{h.date&&<p>{dayLabel(h.date)} · {h.startTime}–{h.endTime}</p>}</li>)}</ol></details>}{r.status==='Alternative'&&<><p>Este horário ainda não está reservado. Ao aceitar, vamos conferir a disponibilidade novamente.</p><button disabled={busy} onClick={()=>void accept()}>{busy?'Conferindo…':'Aceitar este horário'}</button></>}{['Sent','Reviewing'].includes(r.status)&&<p>Aguarde a confirmação da equipe. Seu compromisso atual continua válido.</p>}{error&&<p role="alert">{error}</p>}</article>
}
export function PortalAgenda() {
  const query=usePortal<Appointment[]>('agenda');const requests=usePortal<PortalRequest[]>('requests');const [params]=useSearchParams();const [past,setPast]=useState(false)
  const rows=query.data?.filter(a=>past?a.date<today():a.date>=today())??[]
  return <><header className="portal-title"><h1>Minha agenda</h1><p>Aulas e quadra, tudo no mesmo lugar.</p></header><div className="portal-actions"><Link className="portal-primary" to="/minha-area/solicitar?tipo=Reservation">Solicitar horário</Link><Link to="/minha-area/solicitar?tipo=Trial">Aula experimental</Link></div><nav className="portal-filters" aria-label="Período da agenda"><button aria-pressed={!past} onClick={()=>setPast(false)}>Próximos encontros</button><button aria-pressed={past} onClick={()=>setPast(true)}>Últimas visitas</button></nav><QueryState query={query}/>{!query.isPending&&!query.isError&&!rows.length&&<section className="portal-card"><h2>{past?'Nenhuma visita nos últimos 30 dias':'Nenhum compromisso nos próximos 60 dias'}</h2><p>Se você já tem uma turma ou reserva, peça à equipe para conferir o vínculo com seu cadastro.</p><Link to="/minha-area/ajuda">Conferir meu cadastro</Link></section>}{rows.map(a=><AppointmentCard key={a.key} appointment={a} expanded={a.key===params.get('atividade')}/>)}<section id="solicitacoes"><h2>Minhas solicitações</h2><QueryState query={requests}/>{requests.data?.map(r=><RequestCard key={r.id} request={r}/>)}{requests.data?.length===0&&<p>Suas solicitações e as respostas da equipe aparecerão aqui.</p>}</section></>
}
export function PortalRequestForm({help=false}:{help?:boolean}) {
  const [params]=useSearchParams()
  return <RequestForm key={`${help}:${params.toString()}`} help={help}/>
}
function RequestForm({help=false}:{help?:boolean}) {
  const [params]=useSearchParams();const navigate=useNavigate();const cache=useQueryClient();const options=usePortal<Options>('options');const agenda=usePortal<Appointment[]>('agenda')
  const kind=help?'Help':params.get('tipo')??'Reservation';const appointmentKey=params.get('atividade');const original=agenda.data?.find(a=>a.key===appointmentKey)
  const { user }=useAuth(); const draftKey=`lb-portal-request-v1:${user?.id}:${kind}:${appointmentKey??''}`
  const [draft]=useState(()=>{try { const saved=JSON.parse(sessionStorage.getItem(draftKey)??'null'); return saved && typeof saved.operationId==='string' && ['date','startTime','endTime','message'].every(k=>typeof saved[k]==='string') ? saved as {operationId:string;date:string;startTime:string;endTime:string;courtId?:string;message:string} : null }catch{return null}})
  const [date,setDate]=useState(draft?.date??'');const [start,setStart]=useState(draft?.startTime??'');const [end,setEnd]=useState(draft?.endTime==='24:00'?'00:00':draft?.endTime??'');const [court,setCourt]=useState(draft?.courtId??'');const [message,setMessage]=useState(draft?.message??'');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [uncertain,setUncertain]=useState(Boolean(draft));const operation=useRef(draft?.operationId??crypto.randomUUID());const lock=useRef(false)
  const slot=['Trial','Reservation','Reschedule'].includes(kind)
  const valid=['Trial','Reservation','Reschedule','Cancellation','Help'].includes(kind)
  async function submit(e:FormEvent){
    e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');setUncertain(true)
    const body={operationId:operation.current,kind,appointmentKey,date,startTime:start,endTime:end==='00:00'?'24:00':end,courtId:court||null,message}
    try{sessionStorage.setItem(draftKey,JSON.stringify(body))}catch{/* Current page retains the same intent. */}
    try{await send('/api/v1/me/portal/requests',body);try{sessionStorage.removeItem(draftKey)}catch{/* optional storage */}await cache.invalidateQueries({queryKey:['portal']});navigate('/minha-area/agenda#solicitacoes')}
    catch(e){if(e instanceof ApiError&&[400,422].includes(e.status)){setUncertain(false);try{sessionStorage.removeItem(draftKey)}catch{/* optional storage */}operation.current=crypto.randomUUID()}setError(messageOf(e))}
    finally{lock.current=false;setBusy(false)}
  }
  if(!valid)return <p>Solicitação não encontrada. <Link to="/minha-area/agenda">Voltar à agenda</Link></p>
  return <><Link to="/minha-area/agenda">← Voltar à agenda</Link><header className="portal-title"><h1>{help?'Preciso de ajuda':`Solicitar ${label(kind).toLocaleLowerCase('pt-BR')}`}</h1><p>{help?'Conte o que aconteceu. A resposta aparecerá nas suas solicitações.':'A equipe vai conferir e responder. Enviar esta solicitação não garante a vaga nem altera seu compromisso atual.'}</p></header>{original&&<section className="portal-card"><h2>{original.title}</h2><p>{dayLabel(original.date)} · {original.startTime}–{original.endTime}</p></section>}
    <form className="portal-card portal-form" onSubmit={e=>void submit(e)}><fieldset disabled={busy||uncertain}>{slot&&<><label>Data desejada<input type="date" required min={today()} value={date} onChange={e=>setDate(e.target.value)}/></label><div className="portal-two"><label>Das<input type="time" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Até<input type="time" aria-describedby="end-time-hint" required value={end} onChange={e=>setEnd(e.target.value)}/></label></div><p id="end-time-hint">00:00 significa meia-noite ao final desse dia.</p><label>Preferência de quadra<select value={court} onChange={e=>setCourt(e.target.value)}><option value="">A equipe pode indicar</option>{options.data?.courts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></>}<label>{help?'Como podemos ajudar?':'Mensagem para a equipe'}<textarea required={help||kind==='Cancellation'} maxLength={1000} rows={4} value={message} onChange={e=>setMessage(e.target.value)}/></label></fieldset>{error&&<p role="alert">{error}</p>}{uncertain&&!busy&&<p>Se a conexão falhou, verifique o envio para recuperar esta mesma solicitação.</p>}<button className="portal-primary" disabled={busy||(['Reschedule','Cancellation'].includes(kind)&&!original?.canChange)}>{busy?'Enviando…':uncertain?'Verificar envio':'Enviar solicitação'}</button></form>{help&&<HelpContact/>}</>
}
export function PortalBar() {
  const {user}=useAuth();const accounts=useQuery({queryKey:['billing',user?.id,'/api/v1/me/billing'],queryFn:()=>apiFetch<Account[]>('/api/v1/me/billing/accounts')});const [error,setError]=useState('');const [busy,setBusy]=useState('')
  async function open(id:string){setBusy(id);setError('');try{const access=await send<{token:string}>(`/api/v1/me/portal/bar/${id}/access`,{operationId:crypto.randomUUID()});window.location.assign(`/cliente#token=${encodeURIComponent(access.token)}`)}catch(e){setError(messageOf(e))}finally{setBusy('')}}
  return <><header className="portal-title"><h1>Bar</h1><p>Peça, acompanhe e aproveite sua visita.</p></header><QueryState query={accounts}/>{(!accounts.isError ? accounts.data : undefined)?.filter(a=>a.kind==='Bar'&&a.state==='Open').map(a=><article className="portal-card" key={a.id}><h2>{a.title}</h2><p>{money(a.payable)} disponível para pagar</p><button disabled={Boolean(busy)} onClick={()=>void open(a.id)}>{busy===a.id?'Abrindo…':'Abrir cardápio e comanda'}</button></article>)}{accounts.data&&!accounts.isError&&!accounts.data.some(a=>a.kind==='Bar'&&a.state==='Open')&&<section className="portal-next"><h2>Vai pedir alguma coisa?</h2><p>Peça à equipe o QR da sua comanda. Você pode pedir pelo celular sem fazer um novo cadastro.</p></section>}{error&&<p role="alert">{error}</p>}<section className="portal-card"><h2>Pagamentos e comprovantes</h2><p>As contas vinculadas ao seu perfil continuam disponíveis depois da visita.</p><Link to="/minha-area/pagamentos">Ver pagamentos</Link></section><HelpContact/></>
}
function ProfileForm({profile}:{profile:Profile}) {
  const {signOut}=useAuth();const cache=useQueryClient();const [name,setName]=useState(profile.name);const [phone,setPhone]=useState(profile.phone);const [reminders,setReminders]=useState(profile.reminders);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false)
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{await send('/api/v1/me/portal/profile',{name,phone,reminders},'PUT');await cache.invalidateQueries({queryKey:['portal']});setMessage('Perfil atualizado.')}catch(e){setMessage(messageOf(e))}finally{setBusy(false)}}
  return <><form className="portal-card portal-form" onSubmit={e=>void save(e)}><label>Como você quer ser chamado?<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label>Telefone com DDD<input inputMode="tel" autoComplete="tel-national" maxLength={11} value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))}/></label><p>E-mail de acesso: {profile.email||'Ainda não vinculado'}</p><label className="portal-check"><input type="checkbox" checked={reminders} onChange={e=>setReminders(e.target.checked)}/> Mostrar lembretes de atividades na minha área</label><p>Essa opção não ativa mensagens por WhatsApp, SMS ou e-mail.</p><button disabled={busy}>{busy?'Salvando…':'Salvar perfil'}</button>{message&&<p role="status">{message}</p>}</form><section className="portal-card"><h2>Meus vínculos com a arena</h2>{profile.links.map(l=><p key={`${l.kind}:${l.sourceId}`}>{l.kind==='students'?'Aluno':l.kind==='rentalGroups'?'Grupo':'Reserva'} · {l.name}</p>)}{!profile.links.length&&<p>Nenhum vínculo cadastrado. Se você já frequenta a arena, peça à equipe para conferir seu cadastro.</p>}<Link to="/minha-area/ajuda">Solicitar correção de cadastro</Link></section><section className="portal-card"><h2>Acesso e segurança</h2><Link to="/minha-area/seguranca">Alterar senha</Link><p>Para recuperar seu acesso ou corrigir o e-mail, peça ajuda à equipe para confirmar sua identidade.</p><button onClick={()=>void signOut()}>Sair da minha conta</button></section></>
}
export function PortalProfile(){const query=usePortal<Profile>('profile');return <><header className="portal-title"><h1>Meu perfil</h1><p>Seu cadastro para aulas, quadra e bar.</p></header><QueryState query={query}/>{query.data&&<ProfileForm profile={query.data}/>}</>}
