import { useState, type FormEvent } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { apiFetch } from '../../lib/http'
import { useAuth } from '../auth/authContext'
import { dayLabel, label, messageOf, send, type Choice, type Options, type PortalRequest } from './api'
import { QueryState } from './ClientPages'
import './portal.css'
function DecisionForm({request:r,onSaved}:{request:PortalRequest;onSaved:(message:string)=>void}) {
  const cache=useQueryClient();const options=useQuery({queryKey:['portal','management-options'],queryFn:()=>apiFetch<Options>('/api/v1/portal/options')});const [action,setAction]=useState(r.status==='Alternative'?'Alternative':'Reviewing');const [reply,setReply]=useState('');const [date,setDate]=useState(r.date);const [start,setStart]=useState(r.startTime);const [end,setEnd]=useState(r.endTime==='24:00'?'00:00':r.endTime);const [court,setCourt]=useState(r.courtId??'');const [teacher,setTeacher]=useState(r.teacherId??'');const [amount,setAmount]=useState(r.amount!=null?String(r.amount):'');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const effectiveCourt = court || (options.data?.courts.length===1 ? options.data.courts[0].id : '')
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await send(`/api/v1/portal/requests/${r.id}/decision`,{version:r.version,action,reply,date:date||null,startTime:start||null,endTime:end==='00:00'?'24:00':end||null,courtId:effectiveCourt||null,teacherId:teacher||null,amount:amount===''?null:Number(amount.replace(',','.'))});await cache.invalidateQueries({queryKey:['portal']});await cache.invalidateQueries({queryKey:['operations']});onSaved('Resposta enviada. O cliente já pode acompanhar a atualização na área pessoal.')}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
  const slot=['Trial','Reservation','Reschedule'].includes(r.kind)
  return <form className="portal-form" onSubmit={e=>void submit(e)}><fieldset disabled={busy}><label>Resposta<select value={action} onChange={e=>{setAction(e.target.value);if(e.target.value==='Confirmed'){setDate(r.date);setStart(r.startTime);setEnd(r.endTime==='24:00'?'00:00':r.endTime)}}}>{r.status!=='Alternative'&&<><option value="Reviewing">Colocar em análise</option><option value="Confirmed">Confirmar solicitação</option></>}{slot&&<option value="Alternative">Propor outro horário</option>}<option value="Declined">Informar indisponibilidade</option></select></label>{slot&&['Confirmed','Alternative'].includes(action)&&<><QueryState query={options}/><div className="portal-two"><label>Data<input type="date" required disabled={action==='Confirmed'} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Valor combinado (R$)<input inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)}/></label></div><div className="portal-two"><label>Início<input type="time" required disabled={action==='Confirmed'} value={start} onChange={e=>setStart(e.target.value)}/></label><label>Término<input type="time" required disabled={action==='Confirmed'} value={end} onChange={e=>setEnd(e.target.value)}/></label></div>{(options.data?.courts.length??0)>1&&<label>Quadra<select required value={court} onChange={e=>setCourt(e.target.value)}><option value="">Selecione</option>{options.data?.courts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label>Professor {r.kind==='Trial'?'':'(opcional)'}<select required={r.kind==='Trial'} value={teacher} onChange={e=>setTeacher(e.target.value)}><option value="">Selecione</option>{options.data?.teachers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p>A confirmação cria ou atualiza a reserva. Uma aula experimental é um encontro individual fora da grade regular. Cobranças continuam no fluxo financeiro existente.</p></>}<label>Mensagem para o cliente<textarea required maxLength={1000} rows={3} value={reply} onChange={e=>setReply(e.target.value)}/></label></fieldset>{error&&<p role="alert">{error}</p>}<button disabled={busy}>{busy?'Salvando…':'Enviar resposta'}</button></form>
}
function CustomerLinks() {
  const {user}=useAuth();const enabled=Boolean(user?.roles.includes('Owner')||user?.permissions.includes('users:manage'));const query=useQuery({queryKey:['portal-candidates',user?.id],queryFn:()=>apiFetch<{users:Choice[];records:{kind:string;sourceId:string;name:string}[]}>('/api/v1/portal/candidates'),enabled});const [person,setPerson]=useState('');const [record,setRecord]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false)
  if(!enabled)return null
  async function submit(e:FormEvent){e.preventDefault();const selected=query.data?.records.find(r=>r.sourceId===record);if(!selected)return;setBusy(true);setMessage('');try{await send('/api/v1/portal/links',{userId:person,kind:selected.kind,sourceId:selected.sourceId});setMessage('Vínculo confirmado. O cliente já pode consultar a agenda.')}catch(e){setMessage(messageOf(e))}finally{setBusy(false)}}
  return <details className="portal-card"><summary>Vincular cliente a aluno, grupo ou reserva</summary><QueryState query={query}/><form className="portal-form" onSubmit={e=>void submit(e)}><p>Confirme a identidade antes de vincular. Nomes iguais não são suficientes. Este vínculo permite consultar e solicitar alterações nos compromissos.</p><label>Usuário<select required value={person} onChange={e=>setPerson(e.target.value)}><option value="">Selecione</option>{query.data?.users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.id.slice(0,8)}</option>)}</select></label><label>Cadastro<select required value={record} onChange={e=>setRecord(e.target.value)}><option value="">Selecione</option>{query.data?.records.map(r=><option key={r.sourceId} value={r.sourceId}>{r.kind==='students'?'Aluno':r.kind==='rentalGroups'?'Grupo':'Reserva'} · {r.name} · {r.sourceId.slice(0,8)}</option>)}</select></label><button disabled={busy}>Confirmar vínculo</button>{message&&<p role="status">{message}</p>}</form></details>
}
export function RequestManagement() {
  const {user}=useAuth();const allowed=Boolean(user?.roles.includes('Owner')||user?.permissions.includes('students:write')&&user?.permissions.includes('projects:write'));const query=useQuery({queryKey:['portal','management',user?.id],queryFn:()=>apiFetch<PortalRequest[]>('/api/v1/portal/requests'),enabled:allowed,refetchInterval:30000});const [done,setDone]=useState(false);const [feedback,setFeedback]=useState('')
  if(!allowed)return <p role="alert">A gestão precisa liberar as permissões de escola e agenda para responder às solicitações.</p>
  const rows=(!query.isError?query.data:undefined)?.filter(r=>done?['Confirmed','Declined','Withdrawn'].includes(r.status):!['Confirmed','Declined','Withdrawn'].includes(r.status))??[]
  return <section className="operation-page portal-management"><header><h1>Solicitações de clientes</h1><p>Confira a agenda e responda sem perder o histórico do pedido.</p></header><CustomerLinks/>{feedback&&<p role="status" className="form-success">{feedback}</p>}<p>Pedidos pendentes não ocupam a quadra. A confirmação confere conflitos e registra a atividade; valores não geram cobrança automática.</p><nav className="portal-filters" aria-label="Filtrar solicitações"><button aria-pressed={!done} onClick={()=>setDone(false)}>Em acompanhamento ({query.data?.filter(r=>!['Confirmed','Declined','Withdrawn'].includes(r.status)).length??0})</button><button aria-pressed={done} onClick={()=>setDone(true)}>Concluídas</button></nav><QueryState query={query}/>{rows.map(r=><article className="portal-card" key={r.id}><div className="portal-card-top"><h2>{r.customerName} · {label(r.kind)}</h2><strong>{label(r.status)}</strong></div>{r.date&&<p>{dayLabel(r.date)} · {r.startTime}–{r.endTime}</p>}<p>Cadastro: {r.userId.slice(0,8)}</p><p>{r.message}</p>{r.reply&&<p>Última resposta: {r.reply}</p>}{r.history&&r.history.length>1&&<details><summary>Histórico do pedido</summary><ol>{r.history.map((h,i)=><li key={i}>{label(h.status)} · {h.reply}{h.date&&` · ${dayLabel(h.date)} ${h.startTime}–${h.endTime}`}</li>)}</ol></details>}{!done&&<details><summary>Responder solicitação</summary><DecisionForm key={r.version} request={r} onSaved={setFeedback}/></details>}</article>)}{!query.isError&&query.data&&!rows.length&&<p>Nenhuma solicitação nesta seleção.</p>}</section>
}
