using LongBeach.Domain.Bar;
using LongBeach.Infrastructure.Bar;
namespace LongBeach.UnitTests;
public sealed class BarTabRulesTests
{
    private static BarTabItem Item(decimal quantity = 1) => new(Guid.NewGuid(), new BarProduct("TEST", "Água", "Água", Guid.NewGuid(), "un", "cx", 1, 10, 2, 1, true, false, 0), quantity, Guid.NewGuid(), true);
    private static BarTabPayment Payment(decimal amount, string method = "Cash") => new(Guid.NewGuid(), Guid.NewGuid(), "hash", amount, method, Guid.NewGuid(), null, amount, null);
    [Fact] public void Requested_item_is_not_consumption_and_cannot_be_delivered() { var item=Item(); Assert.Equal(0,BarTabsService.Calculate([item],[]).Total); Assert.Throws<BarRuleException>(()=>item.Fulfill(DateTimeOffset.UtcNow)); }
    [Fact] public void Accepted_item_can_be_delivered_only_once() { var item=Item(); item.Accept(DateTimeOffset.UtcNow); item.Fulfill(DateTimeOffset.UtcNow); Assert.Equal(10,BarTabsService.Calculate([item],[]).Total); Assert.Throws<BarRuleException>(()=>item.Fulfill(DateTimeOffset.UtcNow)); }
    [Fact] public void Rejection_is_terminal_and_requires_reason() { var item=Item(); Assert.Throws<BarRuleException>(()=>item.Reject("")); item.Reject("Indisponível"); Assert.Throws<BarRuleException>(()=>item.Accept(DateTimeOffset.UtcNow)); Assert.Equal(0,BarTabsService.Calculate([item],[]).Total); }
    [Fact] public void Pending_pix_reserves_the_unpaid_amount_without_claiming_receipt() { var item=Item(3); item.Accept(DateTimeOffset.UtcNow); var cash=Payment(10); var pix=Payment(12,"Pix"); var total=BarTabsService.Calculate([item],[cash,pix]); Assert.Equal(10,total.Paid); Assert.Equal(12,total.Pending); Assert.Equal(20,total.Due); Assert.Equal(8,total.Payable); }
    [Fact] public void Declined_pix_releases_allocation_and_never_approves() { var item=Item(); item.Accept(DateTimeOffset.UtcNow); var pix=Payment(10,"Pix"); pix.Decline(); var total=BarTabsService.Calculate([item],[pix]); Assert.Equal(10,total.Payable); Assert.Equal(0,total.Paid); Assert.Throws<BarRuleException>(()=>pix.Confirm(DateTimeOffset.UtcNow)); }
    [Fact] public void Partial_refund_restores_due_without_erasing_original_payment() { var item=Item(); item.Accept(DateTimeOffset.UtcNow); var cash=Payment(10); cash.Refund(3); var total=BarTabsService.Calculate([item],[cash]); Assert.Equal(7,total.Paid); Assert.Equal(3,total.Due); Assert.Equal(10,cash.Amount); Assert.Throws<BarRuleException>(()=>cash.Refund(8)); }
    [Fact] public void Closing_requires_zero_due_and_no_pending_or_unfinished_orders() { var tab=new BarTab(Guid.NewGuid(),Guid.NewGuid(),null,"Tab"); Assert.Throws<BarRuleException>(()=>tab.Close(1,0,false,DateTimeOffset.UtcNow)); Assert.Throws<BarRuleException>(()=>tab.Close(0,1,false,DateTimeOffset.UtcNow)); Assert.Throws<BarRuleException>(()=>tab.Close(0,0,true,DateTimeOffset.UtcNow)); tab.Close(0,0,false,DateTimeOffset.UtcNow); Assert.Throws<BarRuleException>(()=>tab.Touch()); }
    [Fact] public void Supervisor_discount_reduces_due_and_preserves_gross_consumption() { var item=Item(); item.Accept(DateTimeOffset.UtcNow); var tab=new BarTab(Guid.NewGuid(),Guid.NewGuid(),"Visitante","Tab"); tab.Adjust(3); var total=BarTabsService.Calculate([item],[],tab.Discount); Assert.Equal(7,total.Total); Assert.Equal(10,item.Total); Assert.Equal(7,total.Payable); }
    [Fact] public void Snapshot_is_unchanged_when_state_is_corrected() { var item=Item(2); item.Accept(DateTimeOffset.UtcNow); item.Fulfill(DateTimeOffset.UtcNow); item.Reverse("Produto devolvido",true); Assert.Equal(20,item.Total); Assert.Contains("Devolução física",item.Reason); Assert.Equal(0,BarTabsService.Calculate([item],[]).Total); Assert.Throws<BarRuleException>(()=>item.Reverse("Repetido",true)); }
    [Fact] public void Reconciled_fee_must_fit_an_approved_payment() { var pix=Payment(10,"Pix"); Assert.Throws<BarRuleException>(()=>pix.Reconcile(1,DateTimeOffset.UtcNow)); pix.Confirm(DateTimeOffset.UtcNow); Assert.Throws<BarRuleException>(()=>pix.Reconcile(11,DateTimeOffset.UtcNow)); pix.Reconcile(0,DateTimeOffset.UtcNow); Assert.NotNull(pix.FeeConfirmedAtUtc); }
}
